### ISSUE TITLE
npm start fails on new project from cli on c9

### ISSUE THREAD

**Issue by Steven-Pearce** [facebook/react-360#113]
### Description

stevenpearce:~/workspace/VRSurvey $ npm start

> VRSurvey@0.0.1 start /home/ubuntu/workspace/VRSurvey
> node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start

open browser at http:/localhost:8081/vr/

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/ubuntu/workspace/VRSurvey 

Loading dependency graph...
React packager ready.

Loading dependency graph, done.
Bundling `vr/client.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  98.0% (101/102)...Error: Uncaught error in the transformer worker: /home/ubuntu/workspace/VRSurvey/node_modules/react-native/packager/transformer.js
    at /home/ubuntu/workspace/VRSurvey/node_modules/react-native/packager/src/JSTransformer/index.js:172:33
    at process._tickCallback (node.js:369:9)
Error: Uncaught error in the transformer worker: /home/ubuntu/workspace/VRSurvey/node_modules/react-native/packager/transformer.js
    at /home/ubuntu/workspace/VRSurvey/node_modules/react-native/packager/src/JSTransformer/index.js:172:33
Bundling `vr/client.js`
  Analysing...Error: Uncaught error in the transformer worker: /home/ubuntu/workspace/VRSurvey/node_modules/react-native/packager/transformer.js
    at /home/ubuntu/workspace/VRSurvey/node_modules/react-native/packager/src/JSTransformer/index.js:172:33
    at process._tickCallback (node.js:369:9)

### Reproduction

1) Make a workspace on c9.io
2) npm install -g react-vr-cli
3) react-vr init PROJECT_NAME
4) npm start PROJECT_NAME

### Additional Information

* React VR version: [ "react-vr": "~1.0.0",
    "react-vr-web": "~1.0.0" ]
* Operating System: [UBUNTU/ c9.io ]
* Graphics Card: [Nvidia]
* Browser: [Chrome Latest stable]
* VR Device: [No]

**Comment by andrewimm** [comment]
Odd. Is this on a new project, or have you made some changes to client.js?

I'm wondering if there are issues running the React Native server on c9, as you describe.

**Comment by StevenJNP** [comment]
It's a new project. I deleted the entire workspace and tried again a couple of times. Different errors, but it failed again.

**Comment by nightsurge** [comment]
Similar error, fresh project, can't even load the starter/welcomeToVr:

` ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /WelcomeToVR

Loading dependency graph...
React packager ready.

2017-04-21 13:58 node[94103] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-04-21 13:58 node[94103] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-04-21 13:58 node[94103] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-04-21 13:58 node[94103] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-04-21 13:58 node[94103] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:837:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1222:26)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! WelcomeToVR@0.0.1 start: `node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR!
npm ERR! Failed at the WelcomeToVR@0.0.1 start script 'node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start'.
npm ERR! This is most likely a problem with the WelcomeToVR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get their info via:
npm ERR!     npm owner ls WelcomeToVR
npm ERR! There is likely additional logging output above.`

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart WelcomeToVR@0.0.1
6 info start WelcomeToVR@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info WelcomeToVR@0.0.1 Failed to exec start script
9 verbose stack Error: WelcomeToVR@0.0.1 start: `node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
9 verbose stack Exit status 11
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid WelcomeToVR@0.0.1
11 verbose cwd /Users/jjarnold/playing/WelcomeToVR
12 error Darwin 16.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error WelcomeToVR@0.0.1 start: `node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
17 error Exit status 11
18 error Failed at the WelcomeToVR@0.0.1 start script 'node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start'.
18 error This is most likely a problem with the WelcomeToVR package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start
18 error You can get their info via:
18 error     npm owner ls WelcomeToVR
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by andrewimm** [comment]
We rely on the React Native packager, which in turn uses libraries like FB's Watchman to detect changes in your filesystem. Since these errors are filesystem related, please try installing watchman (as described in https://facebook.github.io/react-native/docs/getting-started.html)

I'll update our documentation to contain the same setup steps. Although watchman is not *required*, I've found in practice that many filesystem errors are resolved when it's installed.

**Comment by nightsurge** [comment]
Thanks @andrewimm, that fixed it for me.
