### ISSUE TITLE
<Text> weight not updating

### ISSUE THREAD

**Issue by darknoon** [facebook/react-360#136]
### Description

1. Create new project `react-vr init graph`
1. open url with `?hotreload`, 
1. edit font weight
1. wat

#### Expected behavior
Font weight updates

#### Actual behavior

Font weight only updates after refresh

### Reproduction

Always

### Solution

Something about `<Text>` is probably broken, maybe not listening to props updates. If I add a key on the `<Text>` component it is able to refresh.

### Additional Information

* React VR version: 1.0.0
* Operating System: Windows
* Graphics Card: GTX 970
* Browser: Firefox Nightly
* VR Device: Oculus Rift

**Comment by darknoon** [comment]
After playing with `react-vr` for a while I've actually seen this a number of times, where after hot reloading, things don't update. Particularly when there was an exception generated by the old code, but also in other instances.

**Comment by marcelosuzumura** [comment]
Me too, particularly when changing implementation in React component lifecycle methods like `componentWillMount`. Only reloading the scene effectively applies the change in code.

**Comment by jgwinner** [comment]
I've seen that a lot - exceptions especially prevent things from reloading.

I've found  FireFox nightly only loads even small background pano's properly about 20% of the time so I bang the 'refresh' key a LOT. I get incomplete loads, or backgrounds that are shifted in color - it's all very weird..

Samsung VR seems to be a lot more stable. Then again, my desktop rig is typically really hammered (I have a ton of web pages open), and browsers aren't always the most stable of apps in terms of memory leaks. The fact that the Gear VR seems to work  OK means it's probably Nightly. I'll raise a bug over there.

== John ==
