### ISSUE TITLE
How to set background color for the scene?

### ISSUE THREAD

**Issue by darknoon** [facebook/react-360#137]
### Description

I tried this code with the default project, but the background is still black:
```
      <View style={{
        backgroundColor: "blue",
      }}>
      ...
```

#### Expected behavior
Everything is blue

#### Actual behavior

Still black 

### Reproduction

Always

### Solution

If this isn't the way to do this, the docs should be updated.

### Additional Information

* React VR version: 1.0.0
* Operating System: Windows
* Graphics Card: GTX 970
* Browser: Firefox Nightly
* VR Device: Oculus Rift

**Comment by mikearmstrong001** [comment]
Can you show more of the example as this worked for me

```
    return (
      <View
        style={{
          transform:[{translate: [0, 0, -3]},{rotateX: '10deg'}],
          position:'absolute',
          backgroundColor: 'blue'
        }}>
        <Text>TEST</Text>
      </View>
    );
```

**Comment by darknoon** [comment]
@mikearmstrong001 I just started with an empty project and tried to set the whole scene background to blue. It seems like `View` creates a `Plane` internally if you set the background color.

This seems conceptually weird since in React VR Views can contain 3d objects. Anyway, I'm still just trying to set the `glClearColor` essentially and this doesn't do that, but I don't know what does.

**Comment by mikearmstrong001** [comment]
I see, the use in the example is the backgroundColor of the View - a 2d quad and not the glClearColor.

We don't currently expose the glClearColor but it seen a perfectly reasonable request which I would handle like below. Note the use of `Scene` a special component. I'll add this

```
 return (
      <Scene
        style={{
          backgroundColor: 'blue'
        }}>
        <Text style={{
          transform:[{translate: [0, 0, -3]},{rotateX: '10deg'}],
          position:'absolute'
       }}>TEST</Text>
      </Scene>
    );
```

**Comment by darknoon** [comment]
@mikearmstrong001 I think that seems reasonable, though it would really help if the example started with `<Scene>` since the docs aren't very clear on what it's for.

**Comment by makiJS** [comment]
+1 for @darknoon question

**Comment by broncha** [comment]
I get 
```
Invalid props.style key `backgroundColor` supplied to `Scene`
```

**Comment by breadadams** [comment]
The `<Pano/>` component takes a `tintColor` style prop. So looking around in the following setup shows a full gold background! 🎊 😄 

![image](https://user-images.githubusercontent.com/5795227/29994873-01959bf6-8fdb-11e7-9ac0-0caf6e6f3240.png)

```
<Scene>
  <Pano
    style={{
      tintColor: 'gold',
    }}/>
  <View style={{
    // ...
  }}>
    <Text style={{
      // ...
    }}>colored background!</Text>
  </View>
</Scene>
```
