### ISSUE TITLE
Add search to the documentation

### ISSUE THREAD

**Issue by Haroenv** [facebook/react-360#158]
### Description

*Disclaimer: I work for Algolia*

Adding [docsearch](https://community.algolia.com/docsearch/) to the documentation is something that doesn't take a lot of time, and can have a huge impact on users.

This is done for other fb Open Source projects (React, Jest, Yarn ...) 

cc @cpojer 

#### Expected behavior

There's a search field in the header that searches through all documentation

#### Actual behavior

There's no search on the documentation

### Solution

Apply to docsearch, add it to the page.

**Comment by andrewimm** [comment]
We already have most of the templating stolen from the RN repo, would love to get this kicked off.

**Comment by Haroenv** [comment]
It can be done manually too by making a PR [here](https://github.com/algolia/docsearch-configs/tree/master/configs) with the same/similar configuration as RN
