### ISSUE TITLE
VrButton focus

### ISSUE THREAD

**Issue by Jermorin** [facebook/react-360#163]
Hi ! 

Firstly, thanks for this amazing product, many ideas have emerged. 

Is it possible to instead use vrButton with a long focus without needing to press the button ? 

Thanks,

**Comment by tomaszlakomygp** [comment]
That's a great idea, it could be an optional prop that could be passed to `VRButton` to enable such behaviour.

**Comment by MrKanthaliya** [comment]
@amberroy Would be great to have it. Even I have couple of use cases in current project where it will help.
