### ISSUE TITLE
Change default language of UI.

### ISSUE THREAD

**Issue by HeinPauwelyn** [facebook/react-360#179]
### Description

I'll make an application in two languages: Dutch and French. When the site is loaded, I'll change the text <kbd>View in VR</kbd> to respectively <kbd>Bekijk in VR</kbd> or <kbd>Voir en VR</kbd>. For that I'll use browser detection.

I'll also have a button to change the language manual. Like on image below. The second button is the language button to change the language.

![image](https://cloud.githubusercontent.com/assets/16222780/25772322/9bd45e30-3268-11e7-9a48-84b9fee145f4.png)

Also in the `index.vr.js` code must I get the selected language used for the voice overs in the application.

#### Expected behavior

An easy way to change the language of the application.

#### Actual behavior

There is no

### Side road

For now I've added this code in a new JavaScript file that is linked to the index HTML page.

```js
document.addEventListener("DOMContentLoaded", function () {

    var language = navigator.language || navigator.userLanguage;
    switch (language.toLowerCase()) {
        case "nl-be":
        case "nl-nl":
        case "nl":
            document.querySelector("div a span[style]").innerHTML = "Bekijk in VR";
            document.querySelector("html").setAttribute("lang", "nl");
            document.querySelector("#language span").innerHTML = "Taal";
            break;

        case "fr-be":
        case "fr-fr":
        case "fr":
            document.querySelector("div a span[style]").innerHTML = "Voir en VR";
            document.querySelector("html").setAttribute("lang", "fr");
            document.querySelector("#language span").innerHTML = "Langue";
            break;

        default:
            break;
    }
});
```

On the index page I've added this code:

```html
<div class="optiongroup">
    <button id="language">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4 24h-2v-24h2v24zm18-21.387s-1.621 1.43-3.754 1.43c-3.36 0-3.436-2.895-7.337-2.895-2.108 0-4.075.98-4.909 1.694v12.085c1.184-.819 2.979-1.681 4.923-1.681 3.684 0 4.201 2.754 7.484 2.754 2.122 0 3.593-1.359 3.593-1.359v-12.028z"/></svg>
        <span></span>
        <ul class="optiongroup__option">
            <li>Nederlands</li>
            <li>Français</li>
        </ul>
    </button>
</div>
```

### Solution

Add an option to change the default language of the application

### Additional Information

* **React VR version:** 1.0.0/later than 1.0.0

**Comment by andrewimm** [comment]
I'll add these as flags at init time! Thanks for raising this.

**Comment by andrewimm** [comment]
Overlay is now override-able in React 360
