### ISSUE TITLE
Device Compatibility

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-360#272]
Hi, what is the best way to check if a device will run the react-vr app. Thinking of redirecting to my other web app if it wont work.

**Comment by mikearmstrong001** [comment]
can you be more specific on features you are using as this will help me give a more concrete reply

**Comment by hjnieuwenhuizen** [comment]
Apologies. I am using the pano component that when used with mobile you can just point the phone around to change direction, pitch etc. Yet on a friends phone just rendered the pano pointing the the bottom. I assume its compatibility issue. My question is how do i know if a phone support this feature or not.

**Comment by mikearmstrong001** [comment]
the phone details would be useful, screenshot, console log dump?
There is nothing specific I can think of related to compatibility related to a simple panel so probably the best place is to understand where things are now

**Comment by hjnieuwenhuizen** [comment]
I think it comes down to the phone having a gyroscope. The pano just loads pointing to the ground. My first instinct was to have to webapps for users that have older phones, but now I asked a seperate question if there is a option to which off the gyroscope functionality as users still want to use the webapp laying in bed (example).

**Comment by andrewimm** [comment]
While it would be easy to add a flag to enable / disable the controls, I'd actually like to pursue a better init-time configuration of the `Controls` used by the player (replacing a one-off solution with a more powerful general one). Should be able to throw something together soon.

**Comment by hjnieuwenhuizen** [comment]
Hi Andrew, appreciate the help. This is a huge speed bump for me and is the only thing stopping us from going live. Pano just loads point to the ground and the app is unusable. Just not sure how to handle devices that do not support the gyroscope functionality to pan around. If you have any temporary solution to how i should handle this please let me know.

**Comment by andrewimm** [comment]
If you're using the latest version of React VR, you should still be able to pan around using your finger, regardless of what the device orientation APIs output.

**Comment by hjnieuwenhuizen** [comment]
Thank you Andrew, I will update the packages and let you know. One more question on device compatibility. If i had to create a react-native app for IOS and android and use the WebView component to bring in my react-vr web app, will this work or is this unexplored territory? I am trying to use one code base for all platforms.

**Comment by andrewimm** [comment]
The individual enable/disable/access of control schemes is now fully supported in React 360
