### ISSUE TITLE
Texture Mapping on inside of Cylinder

### ISSUE THREAD

**Issue by upressplay** [facebook/react-360#295]
--- Delete everything above this line before submitting your issue ---

### Description

Building out an environment that has a Pano object. But, then I want to use a Cylinder object that surrounds the Camera to give another level of depth. I can see the texture transparent png on the outside of the cylinder, but when I move it to surround the camera, the texture is not visible. Ie. you can only see it on the outside, not the inside. How can I map the texture image to the inside AND outside of a Cylinder?

Is this a Bug or a Feature Request?
I guess this is a feature request, but it could just be a missing attribute in the documentation.

#### Expected behavior
Map a texture to the inside of a Cylinder. 

#### Actual behavior
Texture is only visible on the outside of a Cylinder.

### Reproduction

<Cylinder
          radiusTop={5}
          radiusBottom={5}
          dimHeight={20}
          segments={100}
          lit={true}
          texture={asset('foreground.png')}
          style={{
                    opacity:.999,
                    transform: [{translate: [0, 0, -10]}],
                  }}
        />

### Solution

Was looking for an attribute similar to 3d programs that would allow you to map on both sides of a Cylinder.

**Comment by mikearmstrong001** [comment]
With 3d graphics you typically render the outer surfaces. Since the view is inside the surface I would recommend add a negative scale to the transform.

```
transform: [{translate: [0, 0, -10]}, {scaleX:-1}],
```

**Comment by upressplay** [comment]
That did the trick. Thank you, Mike! Now, how do I keep the texture off the top and bottom of the cylinder?

**Comment by mikearmstrong001** [comment]
Sorry you caught me when I was going on vacation so I dropped the ball.

Do you mean have no geometry in top and bottom ?

**Comment by andrewimm** [comment]
This is now supported with Cylinder Surfaces in React 360
