### ISSUE TITLE
[Question/Feature Request] 3D world-coordinates on events

### ISSUE THREAD

**Issue by timoxley** [facebook/react-360#296]
What is the recommended approach for converting input events back into 3d world coordinates? Is there a built-in api? Since the camera is not readily available in components it appears a bit of nuisance to do this translation.

Could the 3d coordinates be attached to the event? Would also be good to have access to the ray intersection data.

**Comment by mikearmstrong001** [comment]
What sort of data are you after on the ray test ?
- direction
- origin
- distance to hit component ?

we try to keep the camera out of the react code as much as possible because it is updated at a far faster rate, we could explore a subset of the information from the camera at the time of the event. Input on requirements would be super useful, thanks

cc @andrewimm

**Comment by timoxley** [comment]
Placement and manipulation of objects in 3d space.

E.g. click a point on the Pano, have an object appear at that point. Be able to drag/drop that object to a different position. For decent drag and drop, you need to know exactly where on the object the item was grabbed from so you can transform it relative to that position.

I believe it would be possible to implement this purely on the react side, if the 3d coordinates of the input event were available.

Understood regarding the camera, that makes sense. Is there a technical reason to avoid sharing 3d coordinates for input events with the react worker?

**Comment by franzejr** [comment]
@timoxley  I was trying to figure out how to do that, and I found this thread. I think having the coordinates from the click will be a great feature!

**Comment by andrewimm** [comment]
There are no plans to pass 3D coordinates on events at this time, since most behaviors involving 3D repositioning should be handled outside the React event loop.
