### ISSUE TITLE
Docs:  explain transform : matrix for rotation

### ISSUE THREAD

**Issue by Frazer** [facebook/react-360#321]
Documentation request:

https://facebook.github.io/react-vr/docs/3dcoordinates-and-transforms.html#transform-properties

the explanation of matrix transformations for rotations is unintuitive to me.  
ie:  why 9 rotation values?
      and how does scaling and rotation work in 1 matrix.

I suggest an example be included showing rotation, scaling and translate in 1 matrix.

Thank you.

**Comment by mikearmstrong001** [comment]
Thanks for your input, generally we find people use the higher level properties such as rotateX, rotateY and rotateZ. The full access of a matrix is provided to gain extra control.

So I understand is it that you are don't understand the text or that you are unfamiliar with the properties of matrices in this use case. If it is the former I'd greatly accept suggestions to improve the explanation

**Comment by Frazer** [comment]
I think I understand the text.

A link to explaining matrix manipulation would also be great.

The scale and translate examples seemed clear enough, but the part that seemed unclear is:

scale:  [Sx,0,0,0, 0,Sy,0,0, 0,0,Sz,0, 0,0,0,1]
rotate: [R00,R01,R02,0, R10,R11,R12,0, R20,R21,R22,0, 0,0,0,1]

It is unclear to me how Sx and R00 would be differentiated.  Also, why 9 rotation values?

Perhaps you could link to something like:
http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-17-quaternions/#quaternions
http://www.opengl-tutorial.org/assets/faq_quaternions/index.html#Q27

**Comment by andrewimm** [comment]
Docs reflect this information now

**Comment by babahh** [comment]
Where could I find the Docs about matrix rotation?
