### ISSUE TITLE
Model statement takes Obj and gltf2? Docs state only Obj.

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-360#338]
### Description

Doc and code innacuracy: the code at https://github.com/facebook/react-vr/blob/master/Libraries/Mesh/Model.js and the docs at:
https://facebook.github.io/react-vr/docs/model.html 

both mention Obj as the supported format.

Down in loaders, we see a reference to GLTF:

react-vr/ReactVR/js/Loaders/GLTF2ModelLoader.js

Issue 320 mentions they are supported and gives an example:

https://github.com/facebook/react-vr/issues/320 

#### Expected behavior
If GLTF is supported, the docs should mention it; probably still catching up, so I'll put this in as a reminder.

#### Actual behavior

I checked the secondary documentation, and it's in there.

You know, the secondary documentation:

GLTF2ModelLoader.js

:)

**Comment by andrewimm** [comment]
The code is in master, but it hasn't actually been released into any stable versions yet. We're waiting on v2.0.0 to ship it to the public. It might get confusing if we mentioned GLTF in the docs but no users could actually use it ;)

**Comment by jgwinner** [comment]
Ah! Got it. That's funny as gltf was mentioned in #320 as a solution to bump maps.

How soon will v2.0.0 be out? I'm writing a book. Maybe I should include gltf in the hopes it'll be out when the book hits. I'll add it 'provisionally' I guess.

Maybe I should upgrade to master just to see ... thoughts?

== John ==

**Comment by andrewimm** [comment]
glTF shipped in 2.0.0 yesterday, docs update will come soon

**Comment by jgwinner** [comment]
Yup, cool thanks.

**Comment by jgwinner** [comment]
Just a gentle reminder, I'm running into an issue and I just checked, the doc's still don't mention gltf2. I'll post the issue separately. 

== John ==

**Comment by andrewimm** [comment]
Docs reflect gltf2 usage now

**Comment by jgwinner** [comment]
Thank you Andrew!
