### ISSUE TITLE
Cannot find entry file vr/client.js in any of the roots

### ISSUE THREAD

**Issue by SpaceHexagon** [facebook/react-360#347]
### Description

Fresh app created with react-vr-cli fails to bundle when requested in the browser.
It worked only once and I've tried, clearing npm cache, making a new app and reinstalling node.

#### Expected behavior

Bundle should load. Chess world should appear in browser.

#### Actual behavior

Black screen appears with 2d elements only.
The console shows a bunch of warnings like 
```shell
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: processTransform
  Paths: C:/Code/src/github.com/SpaceHexagon/web\node_modules/react-vr/Libraries/VRReactOverrides/processTransform.vr.js collides with C:/Code/src/githu
b.com/SpaceHexagon/web\node_modules/react-native/Libraries/StyleSheet/processTransform.js
```

and then finally:
```shell
Loading dependency graph, done.
Bundling `vr\client.js`
  Analysing...(node:1472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NotFoundError: Cannot find entry file vr/clie
nt.js in any of the roots: ["C:\\Code\\src\\github.com\\SpaceHexagon\\web"]
```

### Reproduction
```shell
react-vr-cli init TestApp
cd TestApp
npm install
npm start
```

### Additional Information

* 'react-vr' package version: 1.4.0
* 'react-vr-web' package version: 1.4.0
* Operating System: Windows 10
* Graphics Card: NVIDA, proprietary driver
* Browser: Chrome 60.0.3112.113 
* VR Device: Out of VR

**Comment by andrewimm** [comment]
What is the version of your globally-installed react-vr-cli package?

**Comment by SpaceHexagon** [comment]
@andrewimm ```@0.3.5```

**Comment by eapostol** [comment]
bump. it's 2018 was wondering if this was fixed?

**Comment by andrewimm** [comment]
Any issues here should be resolved after the latest underlying RN upgrades.
