### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by adityaparab** [facebook/react-360#361]
### Description
Bug

#### Expected behavior
Project should be accessible on the browser

#### Actual behavior

When I create new project and do npm start, the console says point your browser to `http://localhost:8081/vr/` but when I do the browser says `This site can't be reached`

Additionally I see these errors on console

```
D:\Aditya\playground\vr-test>npm start

> vr_test@0.0.1 start D:\Aditya\playground\vr-test
> node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start

open browser at http://localhost:8081/vr/


'yarn' is not recognized as an internal or external command,
operable program or batch file.
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   D:\Aditya\playground\vr-test

Loading dependency graph...
React packager ready.

jest-haste-map: @providesModule naming collision:
  Duplicate module name: LayoutPropTypes
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\StyleSheet\LayoutPropTypes.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\StyleSheet\LayoutPropTypes.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: NetworkOverlay
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\NetworkOverlay.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\Inspector\NetworkOverlay.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: Text
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\Text.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\Text\Text.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: processTransform
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\processTransform.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\StyleSheet\processTransform.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: YellowBox
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\YellowBox.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\ReactNative\YellowBox.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: TransformPropTypes
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\TransformPropTypes.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\StyleSheet\TransformPropTypes.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: AnimatedImplementation
  Paths: D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js collides with D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\AnimatedImplementation.vr.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: ReactNativeViewAttributes
  Paths: D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\Components\View\ReactNativeViewAttributes.js collides with D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\ReactNativeViewAttributes.vr.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: setupDevtools
  Paths: D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\Core\Devtools\setupDevtools.js collides with D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\setupDevtools.vr.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: View
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\Components\View\View.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\Components\View\View.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: NavigationExperimental
  Paths: D:\Aditya\playground\vr-test\node_modules\react-vr\Libraries\VRReactOverrides\PlatformSpecific\NavigationExperimental.vr.js collides with D:\Aditya\playground\vr-test\node_modules\react-native\Libraries\NavigationExperimental\NavigationExperimental.js

This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph, done.
```
### Reproduction
```
npm install -g react-vr-cli
react-vr init vr-test
cd vr-test
npm start
```
When I point to `http://localhsot:8081/vr/` or `http://localhost:8081/vr/index.html` I get

![image](https://user-images.githubusercontent.com/5561498/31131775-b881ed0a-a878-11e7-9bd5-47f6f8ad9c41.png)

### Additional Information

* 'react-vr' package version: react-vr@1.4.0
* 'react-vr-web' package version: react-vr-web@1.4.0
* Operating System: Windows 10
* Graphics Card: NVDIA GeForce (376.53 Driver)
* Browser: Chrome 61.0.3163.100 (Official Build) (64-bit)
* VR Device: None

**Comment by jgwinner** [comment]
Do you give it a little time? It takes a while for the server to crank up. (and of course Andrew asks good questions).

You can also type

`netstat -a`  to see open ports.

== John ==

**Comment by adityaparab** [comment]
@andrewimm : Yes.. I run my other servers everyday on this computer. I even changed my work project's port to 8081 and I was able to access it when I started that server on 8081. So I'm pretty sure 8081 isn't blocked.
I tried accessing it with `http://127.0.0.1:8081` but got the same result.

On my other computer (mac) it works fine. But on windows 10 it is having this problem.

@jgwinner : Yes sir! I gave it good 2 hours. But still no luck.
Also, I tried `netstat -a` and it shows that port 8081 twice in the list. Is this issue because of that?

```
TCP    0.0.0.0:8009           ADI1234:0             LISTENING
TCP    0.0.0.0:8081           ADI1234:0             LISTENING
TCP    0.0.0.0:8081           ADI1234:0             LISTENING
TCP    0.0.0.0:9080           ADI1234:0             LISTENING
```

as you can see, 8081 is logged twice. While all other ports are logged just once.

**Comment by adityaparab** [comment]
There is another update... I changed default port to `8090` in `vr-test\node_modules\react-native\local-cli\server` file and I am now able to access the project just fine. May be it would be nice if the cli allows for specifying the port on which the project should be run.

I've dug though the codebase and I am certain I can add this feature to the cli.
If I'm allowed to contribute, I'd love to open an issue about it and raise a PR. Please let me know.

**Comment by jgwinner** [comment]
It's not really a React-VR thing, that's a node.js thing - but I'm with you, some docs or a mention would be good. The CLI interface is already there. This command works fine:

'react-native start --port 8090'

I do this all the time to run two worlds side by side for comparison.

**Comment by jgwinner** [comment]
Yup, something is already listenign on port 8081 ... it MIGHT be node.js already running. I've found if you hit break to stop the running instance, it doesn't always exit node.exe. You may need to kill it in the task manager.

Regarding the port change - It's not really a React-VR thing, that's a node.js / React thing - but I'm with you, some docs or a mention would be good. The CLI interface is already there. This command works fine:

`react-native start --port 8090`

I do this all the time to run two worlds side by side for comparison.

A note in the docs that mention "npm start" would be good though, agreed.

== John ==

**Comment by adityaparab** [comment]
@jgwinner Thanks for the updates. So going with the basics of npm, you could just configure port with npm start command like 

```
npm start -- --port 8090
```

I'll create a PR to get this noted in read me file.

Thanks.

**Comment by jgwinner** [comment]
The exact command is:

`react-native start --port 8090`

**Comment by adityaparab** [comment]
@jgwinner That's cool as long as you've installed react-native with a -g. :)
I personally prefer to not install things globally wherever the same thing can be done locally. :)

**Comment by jgwinner** [comment]
Well, I installed it the way the docs said to install it :) 

I thought that syntax you gave was weird, but without the extra -- it sure enough doesn't work. Thanks for the tip!

Understood about the local - less version weirdness then!

== John ==

**Comment by ramuMudunuri** [comment]
hey, just started react vr , the same issue I am getting. I have tried above mention flow but unable to solve the issue.

**Comment by ramuMudunuri** [comment]
> @jgwinner That's cool as long as you've installed react-native with a -g. :)
> I personally prefer to not install things globally wherever the same thing can be done locally. :)

hey, just started react vr , the same issue I am getting. I have tried above mention flow but unable to solve the issue.
any one can please help me to solve this.

**Comment by ramuMudunuri** [comment]
> Well, I installed it the way the docs said to install it :)
> 
> I thought that syntax you gave was weird, but without the extra -- it sure enough doesn't work. Thanks for the tip!
> 
> Understood about the local - less version weirdness then!
> 
> == John ==

hey, just started react vr , the same issue I am getting. I have tried above mention flow but unable to solve the issue.
any one can please help me to solve this.
