### ISSUE TITLE
[Question] Is it possible to play an animation in reverse, as in the animation-direction property of CSS?

### ISSUE THREAD

**Issue by hariKarthic** [facebook/react-360#363]
### Description

Would love it if we are able to play an animation in 'alternate' as soon as it completes.

Currently using two methods to achieve the same effect

       _dropAnimation() {
        this.state.translateValue.setValue(2);
        Animated.timing(this.state.translateValue, {
            toValue: -1.7,
            duration: 1000,
            easing: Easing.linear,
        }).start((...args) => this._riseUpAnimation());
    } 

  
     _riseUpAnimation() {
        this.state.translateValue.setValue(-1.7);
        Animated.timing(this.state.translateValue, {
            toValue: 2,
            duration: 1000,
            easing: Easing.linear,
        }).start(() => this._dropAnimation());
    }

### Solution

Some thing on these lines?

        Animated.timing(this.state.translateValue, {
            toValue: -1.7,
            duration: 1000,
            direction:"alternate",/*THIS*/
            easing: Easing.linear,
        }).start((...args) => this._riseUpAnimation());

**Comment by andrewimm** [comment]
Starting the reverse animation when the first ends is the correct solution
