### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ninjanoka** [facebook/react-360#386]
### Description

I got some issues where video's arent loading on windows edge. Something with a blob url.
Should i load them in a different way? using asset atm.

Regards,
Steven

**Comment by andrewimm** [comment]
Can you provide more information? In order for us to be able to debug the problem, we need to know more about the error you're hitting.

What is the error message or stack trace?

What are the versions of your key npm packages? `react-vr`, `react-vr-web`, `react-native`?

Do the videos load on another browser, like Chrome or Firefox?

**Comment by ninjanoka** [comment]
yes they work on android chrome Firefox. im using react vr & web 1.40 .
The website url is www.kuji.nl i dont see any errors . just one time it said something like cannot load blob url

**Comment by ninjanoka** [comment]
the same behaviour is on iOS btw in chrome and safari

**Comment by jgwinner** [comment]
Worked OK for me.  Opera (oddly), and Firefox.

But, I don't know what you did to generate the error. Can you list exact steps, like which video you are clicking on, what environment (what version of the browser, what O/S, etc?

There's a reason that stuff is at the bottom of every bug report ... they really do need it.

You could upgrade to 2.0 also. I've found it helps a few things.

**Comment by ninjanoka** [comment]
Thanks for the quick reply.

Sure it happens with every video on Edge and my iPads when I click on the play button it does nothing and crashes on iOS safari. Because its so straight forward I thought it was a known issue with maybe a workaround. I will try version 2.0!
 I use : Microsoft Edge 40.15063.674.0 & Microsoft EdgeHTML 15.15063
and on iOS 11 : Mozilla 5/0  applewebkit 304.1.38


I load the video with :  
<Video style={styles.video} source={this.props.video} playerState={this.state.playerState}></Video>
<VideoControl style={styles.videoControl} playerState={this.state.playerState}/>

nothing special.

**Comment by ninjanoka** [comment]
on safari it gives me this error when I press play on one of the videos :  Unhandled promise rejection : NotSupportedError (DOM Exception 9): The operation is not supported.

**Comment by andrewimm** [comment]
Video playback is improved to handle these restrictive browser behaviors in React 360
