### ISSUE TITLE
Detect Language in browser / app with React-vr

### ISSUE THREAD

**Issue by hmontes** [facebook/react-360#396]
Hi

How can i detect the language in the current browser / cell phone (If this is a app) with React-VR. I want to do this WITHOUT a api or server.

I try navigator.language and navigator.userLanguage but both are undefined.

Thank you

**Comment by andrewimm** [comment]
This information is only available in the web worker on Firefox, so to work across platforms you'll need to pass it yourself. You can pass values from the main browser window to React using NativeModules. This example demonstrates a variety of different ways to do this: https://github.com/facebook/react-vr/tree/master/Examples/NativeModules

**Comment by cvan** [comment]
`navigator.language` and `navigator.languages` should give you what you want. Do you have any example/test case somewhere online to show this issue?

**Comment by hmontes** [comment]
Any news about this? I can show online, but if you put in your code navigator.language, that don't work. (Only work when the app is loaded in your browser).

I tried with i18next and i18next-browser-languageDetector but none of them worked.

**Comment by hmontes** [comment]
Finally fixed. Thanks @andrewimm 

After a few months. I understand js much better. So, this is my NativeModule.

```
import { Module } from 'react-vr-web';

export default class BrowserInfo extends Module {
  constructor() {
    super('BrowserInfo');
    // Expose constant values
    this.language = navigator.language || navigator.userlanguage;
  }

  _setRNContext(rnctx) {
    this._rnctx = rnctx;
  }
}

```
