### ISSUE TITLE
<model> gltf2 issue 

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-360#397]
[TeleportGem.gltf.txt](https://github.com/facebook/react-vr/files/1473370/TeleportGem.gltf.txt)

### Description
When I load a gltf (version 2) file that I know works (works in another app), I'm getting an error in a fairly simple app.

#### Expected behavior

I would expect the gltf file to load as it does in my VR Maze:

![image](https://user-images.githubusercontent.com/10425170/32817420-5fdbe488-c972-11e7-92ad-e22948475ab9.png)

#### Actual behavior
When I load this world in FireFox Nightly, I get an error:

```
TypeError: THREE.GLTF2Loader is not a constructor. 
GLTF2ModelLoader.js:109:19
```

### Reproduction
I build an app with `react-vr init SpaceGallery`

I make some changes to index.vr.js

The file is thus:

```
import React from 'react';

import {
  AppRegistry,
  asset,
  AmbientLight,
  DirectionalLight,
  Model,
  Pano,
  Text,
  View,
} from 'react-vr';


export default class SpaceGallery extends React.Component {
  render() {
    return (
      <View>
        <Pano source={asset('BabbageStation_v6_r5.jpg')} />
        <AmbientLight
          intensity={.3}
        />
        <DirectionalLight
          intensity={.7}
          style={{
            transform: [{
              rotateZ: 45
            }]
          }}
        />
        <Model
          source={{
            gltf2: asset('TeleportGem.gltf')
          }}
          lit
        />
        <Text
          style={{
            backgroundColor: '#777879',
            fontSize: 0.2,
            fontWeight: '400',
            layoutOrigin: [0.0, 0.5],
            paddingLeft: 0.2,
            paddingRight: 0.2,
            textAlign: 'center',
            textAlignVertical: 'center',
            transform: [{
              translate: [0, 0, -4]
            }]
          }}>
          Space Gallery
  </Text>
      </View>
    );
  }
};

AppRegistry.registerComponent('SpaceGallery', () => SpaceGallery);

```

I'm attaching the gltf file that generates the error. Note that I used 'TeleportGem.gltf' instead of the above just to make sure I had a known good gltf file. I also double checked for the various materials in static_assets. 
Note: rename the gltf.txt file to gltf

[TeleportGem.gltf.txt](https://github.com/facebook/react-vr/files/1473372/TeleportGem.gltf.txt)

![gazegem_material 001_basecolor](https://user-images.githubusercontent.com/10425170/32817957-6e989c7a-c975-11e7-947d-25fd29729f5c.png)
![gazegem_material 001_metallic](https://user-images.githubusercontent.com/10425170/32817958-6ead4828-c975-11e7-84ab-0304ff7243f1.png)
![gazegem_material 001_normal](https://user-images.githubusercontent.com/10425170/32817959-6ec2fb6e-c975-11e7-990e-0bed6039a47b.png)
![gazegem_material 001_roughness](https://user-images.githubusercontent.com/10425170/32817960-6ed6bb7c-c975-11e7-836d-de9484978969.png)

### Solution

Not sure!

### Additional Information

* 'react-vr' package version:
`-- react-vr@2.0.0

* 'react-vr-web' package version:
`-- react-vr-web@2.0.0

* Operating System:
Windows

* Graphics Card: 
NVidia GTX 1070, not a driver problem

* Browser: 
FireFox Nightly, 59.0a1 (2017-11-14) (64-bit)

* VR Device: 
Desktop / out of headset.

**Comment by larrylin28** [comment]
THREE.GLTF2Loader is import by 'three-gltf2-loader'(https://www.npmjs.com/package/three-gltf2-loader).

**Comment by jgwinner** [comment]
it's done through the React VR model keyword. 

However, I figured out my problem - while working on the book, I had upgraded most projects to 2.0.0

Except this one! it was still 1.4.0, so gltf2 wouldn't work of course.

I'll close the issue.

== John ==

**Comment by jgwinner** [comment]
Actually, it turns out this IS a problem with 2.0.0. I doubted myself.

The cause is that 'three-gltf2-loader' version 1.2 dramatically breaks React-VR; only version 1.1 works.

This happened around on the commit on Oct 22, 2017

They renamed ALL of the objects in three-gltf2-loader from THREE.GLTF2Loader to THREE.GLTFLoader; React-vr-web file: .\react-vr-web\js\Loaders\GLTF2ModelLoader.js uses THREE.GLTF2Loader, not THREE.GLTFLoader; 

### Steps to reproduce:

Given above, but: 
Create a new React-VR app
Attempt to load any GLTF2 model.

### Cause:

In React-VR and React-VR-Web they specify the following package:
"three-gltf2-loader": "^1.0.0"

React-vr-* does not work with 1.2.0, only 1.1.0

### SHORT TERM FIX:

Load "three-gltf2-loader" version 1.1.
In React-vr and react-vr-web, update package.json to specify exact version of 1.1

### LONG TERM FIX:

Either change THREE.GLTF2Loader to THREE.GLTFLoader, or build a built-in GLTF2 importer (in other words, incorporate the three.js sample code.

A third alternative would be for three.js to build their own importer, but with "three-gltf2-loader" there is no need for them to do that.

**Comment by jgwinner** [comment]
For my short term fix I did this in my code's package.json:

    "three-gltf2-loader": "=1.1.0 || > 1.2.1"

**Comment by jgwinner** [comment]
GLTF is completely broken. Is this going to be fixed?

**Comment by andrewimm** [comment]
Sorry for any delays, I completely missed this thread. If the only fix is updating a package.json file, that's easy to handle. PR coming soon.

**Comment by andrewimm** [comment]
To be entirely fair, the issue is that a dependency package we do not own does not comply with semver. We used the carat range, correctly, to only accept minor version updates, and cannot be responsible for an external package that makes breaking changes without updating the major version number.

**Comment by jgwinner** [comment]
Absolutely! It's not a React-VR issue. it did, however, break React VR. Also, I submitted a bug to three-gltf2-loader and haven't heard anything.

So, maybe we should just rewrite it and include in React VR directly; it's based, after all, on a Three.JS sample. I can do this for you, if you want. I'd be happy to help.

**Comment by jgwinner** [comment]
Fixed via React360.
