### ISSUE TITLE
Cannot Find CubeSample

### ISSUE THREAD

**Issue by nacerillo** [facebook/react-360#398]
In the Documentation regarding Native Components the instructions on the cube example make reference to something called CubeSample. I have not been able to find where this CubeSample is located in git, nor what it is. I've also found no reference to it in the examples folder on the git, which is where it was originally supposed to be located. Where is it exactly?

**Comment by andrewimm** [comment]
We should update the docs to point to https://github.com/facebook/react-vr/tree/master/Examples/NativeModules , it's a much better example of the different ways to implement Native Modules.

**Comment by jgwinner** [comment]
It would be handy to have a Native View example too. I'll post an issue about that. I checked this example, but it doesn't address the issue I ran into.

**Comment by mmontag** [comment]
Thanks @andrewimm, please remember to update those docs. :)

**Comment by andrewimm** [comment]
We're actually in the middle of a major docs overhaul. All these things will get picked up when that's complete, don't worry!

**Comment by MariaNattestad** [comment]
Could you add an example of using Three.js within React VR to create a custom shape, or revive the CubeSample so we can see the full code?

**Comment by peterlazzarino** [comment]
@MariaNattestad I have a repo that has an implementation of a native view in React VR if you need something to get you going https://github.com/peterlazzarino/react-vr-world-explorer/tree/master/native-views
