### ISSUE TITLE
Wrong code snippet on ReactVR Docs page (3D Coordinates and Transforms)

### ISSUE THREAD

**Issue by harshalgajjar** [facebook/react-360#408]
### Description
The code provided under "React VR Uses the OpenGL® 3D Coordinate System" sections is as follows:

      <Text style={{ position: 'absolute', transform: [{translate: [0, 0, -6]}],
               layoutOrigin: [0.5, 0.5] }}
      fontSize={0.4} text='Office Lobby' />

I just started learning ReactVR, I'm guessing the above code is for a previous version.

### Solution

It should instead be:

       <Text style={{ position: 'absolute' , transform: [{translate: [0, 0, -6]}],
             layoutOrigin: [0.5, 0.5], fontSize: 0.4 }} >Office Lobby
       </Text>

### Additional Information

* 'react-vr' package version: 2.0.0 
* 'react-vr-web' package version: 2.0.0 
* Operating System: MacOS
* Graphics Card: Intel Iris Pro 6100
* Browser: Safari
* VR Device: -

**Comment by andrewimm** [comment]
Good catch, we moved that into styles between the pre-release and v1.0.0. Feel free to submit a PR

**Comment by RadValentin** [comment]
Already fixed this in https://github.com/facebook/react-vr/pull/385, see commit https://github.com/RadValentin/react-vr/commit/dcbb83b740292d24e007c866cbf42bab4439fdf1

If someone could help review it it would prevent other issues like this being opened.
