### ISSUE TITLE
GLTF is broken since Oct 22

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-360#414]
Per #397 GLTF import of any kind is broken.

If no one is going to take a look, can I rewrite the external module as built-in React VR  code?

**Comment by andrewimm** [comment]
It is resolved in React 360, yes.

**Comment by andrewimm** [comment]
eb59b728f5b41ce4767f9395f3b8dd5222150842

**Comment by jgwinner** [comment]
Right, just looked. Excellent! I closed 397 too.

I did notice that "three-gltf2-loader" is an archived project.

== John ==
