### ISSUE TITLE
Cursor misplaced when Scene is translated

### ISSUE THREAD

**Issue by mciastek** [facebook/react-360#420]
### Description

When `Scene` is moved, cursor behave oddly. It's misplaced. I use SimpleRaycaster (https://github.com/mathdroid/simple-raycaster), which set's raycaster origin to `[0, 0, 0]`. Moving `Scene` alters camera's world position, so it's possible that raycasting is also buggy (need to check it). Because of cursor position computations (https://github.com/facebook/react-vr/blob/da6da09cf491dc9056ebe85fa16c84dc14cdb249/OVRUI/src/UIView/GuiSys.js#L543-L564) changing `Scene` position breaks cursor.

#### Expected behavior
When `Scene` element is translated, cursor should stay in the same place. I translate `Scene` by using `transform` directly in the component, e.g.:

```js
<Scene
  style={{
    transform: [{
      translateX: -1,
    }, {
      translateZ: -1,
    }],
  }},
>
  // Scene children
</Scene>
```

The same behaviour appears when movement is animated.

#### Actual behavior

Cursor should stay in the same place, even if `Scene` was translated.

Before translation:
![screenshot_20171218-180422](https://user-images.githubusercontent.com/3169629/34118134-313a4c20-e41e-11e7-930f-b9b79c3461af.png)
 
After translation:
![screenshot_20171218-180433](https://user-images.githubusercontent.com/3169629/34118119-1e531c9a-e41e-11e7-878e-f133c5b91007.png)

### Additional Information

* 'react-vr' package version: 2.0.0
* 'react-vr-web' package version: 2.0.0
* Browser: Chrome

**Comment by andrewimm** [comment]
Resolved with the better coordinate systems handling in R360
