### ISSUE TITLE
Question - Building npm package for Native View

### ISSUE THREAD

**Issue by peterlazzarino** [facebook/react-360#422]
Hi! Hope you don't mind the question. I've been building up a react-vr app and wanted to wrap some native modules I've created into a small library but am running into an issue and wanted to see if anyone here had thoughts.

I have thrown up a package on npm with a react component and native view but when I try to import them I get an error in my package on import saying that the following import is not available.

import LayoutAndTransformPropTypes from 'LayoutAndTransformPropTypes';

Is there another way I can reference Layout and Transform proptypes from within a library or is this currently not possible? I'm quite new to react-vr and react-native so apologies in advance if I'm missing something obvious. Also my package is being compiled with babel and I've pushed it up with the dist folder here https://github.com/peterlazzarino/react-vr-line if you'd like to take a look.

**Comment by peterlazzarino** [comment]
Update, I was able to get around this issue by fixing my imports but now I get an error document is not defined when trying to import my native view. Am I correct in thinking the source of my problem is likely described here and not currently something I can work around? https://stackoverflow.com/questions/44979827/reactvr-document-is-not-defined

**Comment by andrewimm** [comment]
LayoutAndTransformPropTypes in this case is being imported by a unique identifier using FB's Haste import scheme (how React Native packager works). This only works by default for your actual app code, not secondary packages. To tell the React packager to allow your package to also use haste headers, you'll need to modify the app's `rn-cli.config.js` file, found in the root of the app.
Near the bottom, you'll see a section called `getProvidesModuleNodeModules`. This tells the packager which npm packages are allowed to use Haste imports. You can see that we use it to tell the packager that the `react-vr` package is allowed to use these imports. Add your own package in this section, and you'll be able to use Haste imports as well.
