### ISSUE TITLE
ReactVR panoramic images vs Equirectangular images

### ISSUE THREAD

**Issue by ShaheedLegion** [facebook/react-360#424]
Has any progress been made to support 2D panoramic images in the Pano component?
I'm only using react-vr for this one component and the toolkit looks promising, but 2D panoramic images seem stretched and pixellated using the Pano component, is there a flag/fix I'm missing?

Thanks.

**Comment by jgwinner** [comment]
They work fine for me - are they true 360/180 panos? Most are not quite 180 vertically. You can fix this by adding a strip on the top or bottom. (I actually show exactly how to do this in my book -although it takes some artistry in some cases).

Resolution is also an issue of course, as you're spreading the pixels around a sphere; you want really high resolution.

**Comment by mikearmstrong001** [comment]
I would suggest using a cylindrical component and then placing an image of the correct aspect ratio on this (many 2d panoramic images can be very wide). Using this component you will get a image that wraps around the viewer.

**Comment by ShaheedLegion** [comment]
I see, thanks for the updates.
My images aren't true pano, they're extremely wide - taken using the Cardboard Camera app, which lets you pan the phone in a circle around you while performing the stitching operation, but it takes a wide photo, not equirectangular.

I'll look into both options - extending the top+bottom of the image with a strip, and then wrapping it around a cylindrical component to see if it solves my problem.

Thank you
Regards

**Comment by jgwinner** [comment]
That will work great if you add a "daylight" strip to the top or a 'floor' strip to the bottom. I show both of these in my book although I didn't really have time to include the Vue scene I used to regenerate the sky. It's easier to replace the floor. 

You might also be able to take multiple pano's - just tilt the camera up some, then use a stitcher to put together the views. I experimented with this quite a few years ago; most stitcher's were expensive but I haven't checked recently. 

Of course, the images would have to be somewhat static.

**Comment by mpochiro** [comment]
I’m not sure how wide the photos are or what the quality is but you could treat them before and make them equirectangular. Then just add them and stitch them together. It does sound like extra steps though. The daylight and floor bar seem simpler though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShaheedLegion** [comment]
Hi, both solutions are viable for me right now - I'd like to have true equirectangular images, so I'm leaning towards taking multiple shots and stitching them together in post. The daylight and floor strips would work perfectly for my existing library and would enable me to use a broader range of gallery and display technologies to present my images to users.

Thank you both for the awesome ideas.
