### ISSUE TITLE
How to make my Component / View always show in front of me ?

### ISSUE THREAD

**Issue by sanBastia** [facebook/react-360#434]
How to make my Component / View always show in front of me ? all i want to know is how to make my component following my head direction, always show in front of me 
thank you

**Comment by larrylin28** [comment]
Question: what is the use case you want to do this? 
- If you want to use it on a small visual effect like cursor: 
check the `billboarding` props of <View>(see View.vr.js).
- If you want to use it on a big, intractable menu: 
I would recommend you don't do that. As this kind of menu is not intractable in VR. An better option it to set the transform of the view to align with head rotation when it comes up(check VrHeadModel.js). And just leave it there, don't keep moving it until you want to re-center it next time.
