### ISSUE TITLE
Ray Casting for complex 3d Models

### ISSUE THREAD

**Issue by archik408** [facebook/react-360#444]
### Ray Casting for complex 3d Models

I have several 3d models that created via [photogrammetry](https://en.wikipedia.org/wiki/Photogrammetry) technique. As result this kind of models very complex, they have many triangle and polygons, but looks realistic and great. I have a problem with ray casting when ray intersect this type of complex model I see many lags.

![screenshot from 2018-02-12 13-09-14](https://user-images.githubusercontent.com/10139861/36091759-f148abf8-0ff5-11e8-8a4f-34404cdfd51b.png)

I understand that this is related to intersect math calculation. Can you advise how i can improve or fix this moment? I know, I can aproximate models but may be I can do something with my ray casting implementation?

Below my simple raycasting implementation:
```
import * as OVRUI from 'ovrui';
// import ControllerRayCaster from 'react-vr-controller-raycaster';

class RayCastersModule {
    constructor(/*scene*/) {
        // this.scene = scene;

        this.simpleDotRaycaster = {
            getType: () => 'simpleDot',
            getRayOrigin: () => [0, 0, 0],
            getRayDirection: () => [0, 0, -1],
            drawsCursor: () => true
            // getMaxLength: () => 20
        };
    }

    createRayCasters() {
        const { simpleDotRaycaster/*, scene*/ } = this;
        return [
            simpleDotRaycaster,
            // new ControllerRayCaster({ scene, color: '#ff0000'}),
            new OVRUI.MouseRayCaster()
        ];
    }
}

export default RayCastersModule;
```

**Comment by andrewimm** [comment]
By default, the way Three.js does raycasting is to compare all individual triangles, which creates large lags on complex models. Do you actually want to support ray intersections on these objects, or is it okay to ignore those intersections?
If it can be ignored, we had talked about implementing a style flag that would disabled ray intersections. I can't recall if we implemented it, but I can investigate – I'm confident we used a similar technique on the British Museum virtual tour.

**Comment by archik408** [comment]
it's okay to ignore, I think the style flag will be very helpful

**Comment by larrylin28** [comment]
It may be also helpful to support custom collision mesh(like a cube, capsule, etc) for case that don't want to ignore?

**Comment by archik408** [comment]
@andrewimm Why you close this issue without any comments?

**Comment by andrewimm** [comment]
Due to changes in the raycasting algorithm that were part of the React 360 release, it should no longer be an issue. Let me know if that's not the case.

**Comment by MosiiAUT** [comment]
Hello, I am currently working on a 3D Project and using the simple-raycaster https://www.npmjs.com/package/simple-raycaster to interact with a gaze-button. While this works perfectly fine, I have the problem that the raycast costs me about 30% of my Performance, this means my frames drop down to an average of 25 Frames. My 3D Elements are low-poly though.

@andrewimm do you still have this style flag that I could use? I tried to limit the length of the raycast to only hit the UI elements but it ignores every number I give it.
