### ISSUE TITLE
extending RCTBaseView – frame deltaTime can be NaN

### ISSUE THREAD

**Issue by luruke** [facebook/react-360#449]
### Description
I'm extending RCTBaseView to create a custom view, i'm using `frame` method to update deltaTime for my custom material.

#### Expected behavior
The `deltaTime` should never be `NaN`

#### Actual behavior
In some case the `deltaTime` is `NaN`

![screen shot 2018-03-08 at 16 02 24](https://user-images.githubusercontent.com/61326/37158065-ba14b746-22ea-11e8-9ab0-5761952fd722.png)

### Reproduction

If loading the app in an external tab not active, and leaving it in the background for some time, when activating the tab sometimes the `deltaTime` is NaN

**Comment by andrewimm** [comment]
This should be resolved in the new R360 runtime
