### ISSUE TITLE
Error: bundling failed: "Unable to resolve module

### ISSUE THREAD

**Issue by EkinKucuk** [facebook/react-360#451]
I am trying to use CesiumJs with React-vr but I'm getting this error: 

Bundling `vr\client.js`  [development, non-minified, hmr disabled]  100.0% (121/121), done.
Bundling `index.vr.js`  [development, non-minified, hmr disabled]  0.0% (0/97), failed.
error: bundling failed: "Unable to resolve module `./cesium/CesiumGlobe`

**Comment by andrewimm** [comment]
Sorry, I'm not too familiar with Cesium, so I'm just guessing here. Is CesiumGlobe a file in your own codebase, or within the cesium npm module? Can you find the file where it's being required, and see if it actually exists?

**Comment by EkinKucuk** [comment]
I don't think there is any problem with directory structure and file existence, because it works on ReactJs. However it is not working on React-vr. Maybe React-vr and Cesiumjs are not compatible with each other. Thanks for your interest Andrew.

**Comment by andrewimm** [comment]
React VR is just using the standard packager from React Native, there's nothing special about it. With a better understanding of how your files are arranged, I might be able to help find a solution.

**Comment by EkinKucuk** [comment]
Okay, thank you very much

**Comment by EkinKucuk** [comment]
myProject
|-cesium
|-node_modules
|-vr-|-client.js
|      |-index.html
|-inde.vr.js

This the main structure of my files. For some reasons I cannot share everything I am sorry about that.

In index.vr.js (Where I import the cesium): 

import CesiumGlobe from "./cesium/CesiumGlobe";
import reactLogo from "./logo.svg";
import redsLogo from "./redsLogo.png";
export default class cesiumAndReact extends React.Component {
render() {
	  const {reactLogo, redsLogo, label, line, flyToLocation} = this.state;
	  const containerStyle = {
            width: '100%',
            height: '100%',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
            position: 'fixed',
        };
	  
	return (
      <View style={containerStyle}>
	  <VrButton onEnter={ () => this.animateProgress() }
              onExit={ () => this.stopProgress() }
              onClick={ ()=> this.click() }></VrButton>
			  
			  <CesiumGlobe
                    icons={icons}
                    labels={labels}
                    polylines={polylines}
                    onLeftClick={this.handleLeftClick}
                    flyToLocation={flyToLocation}
                />
                <div style={{position : "fixed", top : 0}}>
                    <div style={{color : "white", fontSize: 40, }}>
                        Text Over the Globe
                    </div>
				</div>	
      
      
      </View>
    );
  }
}
This is the most I can share, I am sorry about that I cannot give furher information. Many thanks.
