### ISSUE TITLE
Cannot place objects at the top or bottom, they get cropped off.  

### ISSUE THREAD

**Issue by ryanf12** [facebook/react-360#464]
### Description

Bug.

#### Expected behavior

If I type in <View style={{width: 200, height:1500, left:500, top:200, backgroundColor: 'rgba(255, 25, 2, .5)'}} /> expect a narrow, tall box, to the right of the center, and above.  

Similarly, if I "transform" an object to the top, I expect it to show up not get cropped off.  

#### Actual behavior

The box gets cropped off, the full height doesn't display.  

If I send any objects above above 3/4 of the page, they get cropped off.  

### Reproduction

An example of your code that reliably reproduces the issue is ideal.

<View style={{width: 200, height:1500, left:600, top:-400, backgroundColor: 'rgba(255, 25, 2, .5)'}} />

### Solution

You should be able to put a button anywhere on the page, including the top or bottom.  

### Additional Information

* 'react-360' package version: npm list react-360
* 'react-360-web' package version: npm list react-360-web
* Operating System: Windows
* Browser: Chrome
* VR Device: Gear360

**Comment by andrewimm** [comment]
The default surface size is 1000px x 600 px. Anything beyond these bounds will be cut off, by design. I will update the docs to make this clearer.

You can modify the size of the surface, as described here: https://facebook.github.io/react-360/docs/surfaces.html#modifying-a-surface
