### ISSUE TITLE
Delete this.  +

### ISSUE THREAD

**Issue by ryanf12** [facebook/react-360#468]
Deleted.

**Comment by andrewimm** [comment]
This error means that your code failed to compile. What is the output in your terminal running the server?

**Comment by andrewimm** [comment]
For future reference, you can close any issue you have created.

**Comment by jgwinner** [comment]
Hey, I've done some embarrassing things too, like X="5" instead of X={5}, but leaving the bones of discouragement for others to gnaw at helps us all!
