### ISSUE TITLE
react-360-gaze-button - isGazed is not defined

### ISSUE THREAD

**Issue by ryanf12** [facebook/react-360#473]
--- Delete everything above this line before submitting your issue ---

### Description

Is this a Bug or a Feature Request?

Bug 

For a Bug please explain below what you did, what you expected to happen, and what actually happens.

I am targeting Gear VR and Oculus Go devices.  It is important that a boilerplate cursor is available so that  users can click and interact with content.  By default, the cursor is hidden on VR devices and the VR controller raycasters for Gear VR and Oculus Go devices are not included in React-360.  

I added "react-360-gaze-button" (https://www.npmjs.com/package/react-360-gaze-button) so that users can click on and interact with things when wearing the VR goggles.  

I expected the cursor to show up in the center of the screen, where a user can gaze at a component to click.  

![gaze](https://user-images.githubusercontent.com/38990999/39881159-1107e28c-544e-11e8-8c0b-6f9b1b64c294.jpg)

The remainingTime is updating correctly, and I'm getting the error "isGazed is not defined" instead of a click event.  

![react](https://user-images.githubusercontent.com/38990999/39881124-f2b6959e-544d-11e8-8dab-807661df8f80.jpg)

I started with the "hello world" sample, and added in the example provided at the NPM page.  

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

Created the project, added gaze-button with "npm i --save react-360-gaze-button".  Imported to project (import GazeButton from "react-360-gaze-button";) added in the 'gaze button' specific code.  

An example of your code that reliably reproduces the issue is ideal.

`import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-360';

import GazeButton from "react-360-gaze-button";

class gaze extends React.Component {
  state = {
    clicked: false
  };
 
  render() {
    const { clicked } = this.state;
    return (
	<View style={styles.panel}>
      <GazeButton
        onClick={() => this.setState({ clicked: true })}
        duration={2000}
      >
        {(remainingTime, isGazed, gazeTimestamp) => (
          <Text>
            {isGazed
              ? clicked
                ? "You have clicked me"
                : `Gaze me for ${remainingTime} milliseconds`
              : "I am a gaze button"}
          </Text>
        )}
      </GazeButton>
	</View>
    );
  }
}

const styles = StyleSheet.create({
  panel: {
    // Fill the entire surface
    width: 1000,
    height: 600,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  greetingBox: {
    padding: 20,
    backgroundColor: '#000000',
    borderColor: '#639dda',
    borderWidth: 2,
  },
  greeting: {
    fontSize: 30,
  },
});

AppRegistry.registerComponent('gaze', () => gaze);
`
Ideally, I'd like to be able to use a cursor so that users wearing VR devices can interact with content.  The dot that Oculus uses is fine, it is not visible in VR mode, however.  

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

Some documentation on how to install a cursor/controller for VR devices would be helpful.

**Comment by andrewimm** [comment]
> By default, the cursor is hidden on VR devices and the VR controller raycasters for Gear VR and Oculus Go devices are not included in React-360.

Can you explain further? We provide first-class support for Oculus Browser on both Gear VR and Go, and I can personally note that I test on Go every day. Sometimes you need to press a button on the controller for security reasons, but it should show up after that. If I'm missing something, it'd be good to know what that is.

Second, unfortunately we don't provide the `react-360-gaze-button`, so I can't provide any support there. You should follow up with the developer, though the github repo linked to that package doesn't seem to be active.

**Comment by mathdroid** [comment]
Sorry for replying to closed issue, but the `isGazed` issue mentioned by @ryanf12  in `react-360-gaze-button` was fixed in [`v1.0.0`](https://github.com/mathdroid/react-360-gaze-button/blob/master/package.json) of `react-360-gaze-button`. :)
