### ISSUE TITLE
Why native mdoules doesn't seem to return some native objects(window, navigator, and etc...) in promise by invokeCallback method?

### ISSUE THREAD

**Issue by venoral** [facebook/react-360#474]
Hello, I tried return "battery" object in promise resolve by invokeCallback method  in NativeModules sample,  but get an empty object on the React side, then I also tried other native objects, such as window, navigator, are not feasible.Why can I visit but can't return it?

### Description
![14cce61f79bc75d14adaa2392e464c86](https://user-images.githubusercontent.com/14950800/39913767-a06dd228-5535-11e8-9e30-d39ec3db80fd.jpg)
![03cc17cea3c4cd142b0a8e75a06cc186](https://user-images.githubusercontent.com/14950800/39913768-a29c2eb4-5535-11e8-8af4-219ec65c86b9.jpg)
![9cc204ad3c80afddd6125cd490701db0](https://user-images.githubusercontent.com/14950800/39913769-a3e5beca-5535-11e8-9345-b8b24ec1c5de.jpg)

Looking forward to your reply, thx!😝

**Comment by andrewimm** [comment]
React 360 runs its code in two separate contexts: one for app execution, and one for rendering. This is a big part of what allows us to do fast VR rendering in a web browser. The main browser window needs to be connected to the rendering processes, so the app code (your React code) lives in the separate process (a Web Worker).
You can learn more about Web Workers here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers
To communicate between the two contexts, we pass messages. However, browsers have restrictions on what can be passed – only primitive values like strings, numbers, booleans, and objects that can be copied, like Arrays and plain Objects, can be transferred. The algorithm that transfers these values is described here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

So unfortunately, it's a limitation of web browsers, not something we can fix within the framework.
