### ISSUE TITLE
Reopen the website of React VR.

### ISSUE THREAD

**Issue by zzc-tongji** [facebook/react-360#478]
I am very glad to see that your team has upgraded React VR to React 360.

**However, could you reopen the website (document) of React VR?**

I am developing a project based on React VR, and for some reasons (#471 and #472) it could not be upgraded to React 360 at this time. So I usually have to look up the website of React VR, but it is now replaced by React 360.

**Comment by andrewimm** [comment]
The legacy documentation is available here: https://github.com/facebook/react-360/tree/2f1d3b9b138fea0b551a173ccd511ef92c9d0330

You should be able to just download the repository and view the documentation.
