### ISSUE TITLE
Is the code here has a bit wrong in your MultiRoot sample?

### ISSUE THREAD

**Issue by venoral** [facebook/react-360#481]
Sorry, your code here seems a bit wrong.

### Description

In Store.js file, when each component is initialized through the connect method, its own _listener method is registered for the global listeners collection. When the updateComponents method is executed to update the state of each component, the previously added _listener is executed. Since the call is in the global environment, so "this" object at this time is not the component itself, but the instance object of DedicatedWorkerGlobalScope(see the console can be printed out).
So I think the component should add itself (this) instead of its own _listener method when registering.

<img width="922" alt="2018-05-15 4 20 09" src="https://user-images.githubusercontent.com/14950800/40045076-ebddb830-585b-11e8-99e8-fe2652906bdd.png">

**Comment by andrewimm** [comment]
How did you build and run the project? I just ran the sample code and confirmed that it still works as intended, and that the context of the listener is the `Wrapper` component.

**Comment by venoral** [comment]
emmm... I'm sorry to bother you😅, contrast found to be my code's error,  I did not use the arrow function for the _listener method...so...the "this" object is not bound to _listener method. I am really sorry...
