### ISSUE TITLE
AudioContext not found in Safari Browser

### ISSUE THREAD

**Issue by BerndHuber** [facebook/react-360#486]
When initiating a react instance with react 360 in Safari, I am getting the AudioContext error.

I instantiate like this:

```
import {ReactInstance} from 'react-360-web';

function init(bundle, parent, options = {}) {
  const r360 = new ReactInstance(bundle, parent, {
    fullScreen: true,
    ...options,
  });
}
window.React360 = {init};
```

And the error stack in the bundle is this:
1.

> n = new r.ReactInstance(e, t, babelHelpers.extends({ fullScreen: !0 }, o));

2.

> this.runtime = new U.default(this.scene, (0, o.default)(t), l), this.vrState = new p.default, this.vrState.onDisplayChange(function(e) { e ? a.overlay.setVRButtonState(!0, "View in VR", a.enterVR) : a.overlay.setVRButtonState(!1, "No Headset", null) }), this.controls.addCameraController(new g.default(this._eventLayer)), this.controls.addCameraController(new v.default(this._eventLayer)), this.controls.addCameraController(new b.default(this._eventLayer)), this.controls.addEventChannel(new L.default(this._eventLayer)), this.controls.addEventChannel(new V.default(this._eventLayer)), this.controls.addEventChannel(new P.default), this.controls.addEventChannel(new H.default), this.controls.addRaycaster(new z.default), this.controls.addRaycaster(new A.default(this._eventLayer)), this.controls.addRaycaster(new Q.default(this._eventLayer)) }

3.

> "function" == typeof a ? this.context.registerModule(a(this.context)) : this.context.registerModule(a)

4.

> nativeModules: [new B.default(this.compositor.getEnvironment()), function(e) { var t = new T.default(e); return a._audioModule = t, t }, function(e) {

5.

> return a._audioCtx = new AudioContext, a._audioData = {}, a._handles = {}, a._loaders = {}, a._rnctx = e, a //////////--->>>Can't find variable: AudioContext

How can I use React 360 for Safari correctly? Is there any way to turn off the audio modules?

### Additional Information

* 'react-360' package version: 1.0.0
* 'react-360-web' package version: 1.0.0
* Operating System: MacOS
* Browser: Safari and any iPhone Browser
* VR Device: not tested

**Comment by andrewimm** [comment]
This was an oversight on my end, will ship a fix asap

**Comment by BerndHuber** [comment]
Excellent, thanks! Is there a fix to this in the meanwhile, eg. how to do 

> react-360 init

 without AudioModule?

**Comment by andrewimm** [comment]
Shouldn't matter, just pushed react-360-web v1.0.1 to npm with fixes :) Confirmed it works on the last 2 versions of Safari.
