### ISSUE TITLE
Uncaught TypeError: r360.mountToLocation is not a function

### ISSUE THREAD

**Issue by lilybarrett** [facebook/react-360#491]
### Description

I'm converting a legacy React VR app over to using React 360, and I initially followed the [docs](https://facebook.github.io/react-360/docs/from-react-vr.html) (minus the part re: creating an entirely new app and moving my files over, which I honestly wanted to avoid). The docs mentioned mounting the legacy app to the new React 360 runtime by doing the following:

```
Since all React VR code is built in a 3D coordinate system oriented around (0, 0, 0), you should mount your legacy app to the system's default 3D location.

r360.mountToLocation(
  r360.createRoot('MyLegacyApp'),
  r360.getDefaultLocation(),
);
```

I added this code to my `index.js` as such:

```
import { ReactInstance } from "react-360-web";

function init(bundle, parent, options = {}) {
  const r360 = new ReactInstance(bundle, parent, {
    fullScreen: true,
    ...options,
  });

  r360.mountToLocation(
    r360.createRoot(SubstituteYourAppName'),
    r360.getDefaultLocation(),
  );
}

window.React360 = {init};
```

#### Expected behavior

I'd hoped this would successfully mount my legacy app to the new system's default 3D location (in addition to giving me other benefits related to the new runtime).

#### Actual behavior

The app failed to load at all, and when I opened my browser console, I saw the following error:

```
Uncaught TypeError: r360.mountToLocation is not a function
    at Object.init (client.js:19)
    at index.html:13
```

I then experimented a bit and wound up successfully getting my app to load by removing the `mountToLocation` code and, in its place, using:

```
r360.renderToSurface(
     r360.createRoot('SubstituteYourAppName, { /* initial props */ }),
     r360.getDefaultSurface()
);
```

But the app does not mount to the correct default location in the React 360 environment, which seems to result in the default cylindrical surface _not_ being perfectly centered in front of the user.

I got around this somewhat by transforming my elements to be approximately centered, but obviously, this is less than ideal.

Would love any insight on what could be going wrong here, specifically with the use of `mountToLocation`.

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.0
* Operating System: MacOS Sierra
* Browser: Chrome

**Comment by andrewimm** [comment]
Ah, this is a typo on my end, it should be renderToLocation. Will update the docs.

**Comment by andrewimm** [comment]
More on this here: https://facebook.github.io/react-360/docs/objects.html#locations

**Comment by lilybarrett** [comment]
Awesome, thank you so much, @andrewimm!
