### ISSUE TITLE
How to deploy with nodeJS.

### ISSUE THREAD

**Issue by leo1mml** [facebook/react-360#493]
How do I deploy react360 cli apps with nodeJS, in heroku if possible.
I tried building the app with bundle and listen it with a server.js file, but it only works in localhost, when I deploy into heroku it builds ok, but it goes 503 Unavailable.

**Comment by andrewimm** [comment]
React 360 is all client-side code, nothing about it is specific to NodeJS, Heroku, or any server. You need to treat it the same way you would treat an HTML, CSS, or image file – it probably goes in a `public` directory in your server application, and gets copied directly to Heroku's static asset buckets.

**Comment by isahboy1** [comment]
I am using namecheap server to host my every work i do to my client. And i went to deploy my React 360 project on the same server.But they are using Nodejs.So please how can i deploy me project on the namecheap server
