### ISSUE TITLE
No transform named scaleZ 

### ISSUE THREAD

**Issue by Pluto8195** [facebook/react-360#506]
### No feature for scaleZ transformation

On the docs there is a description of possible transforms for an entity, rotate, scale, translate.
all of the transforms work as expected except for _scaleZ_

upon looking through the repo, ive noticed scaleX and scaleY are implemented but not scaleZ
so this is either a feature request for that or a mistake that it wasn't included in the repo 

### The code im running

```
<Entity
          source={{obj: 'file.obj'}}
          style={{transform:
            [
              {translateX: this.state.tX},
              {translateY: this.state.tY},
              {translateZ: this.state.tZ},
              {scaleX: this.state.sX},
              {scaleY: this.state.sY},
              {scaleZ: this.state.sZ},
              {rotateX: this.state.rX},
              {rotateY: this.state.rY},
              {rotateZ: this.state.rZ},

            ],
              color: 'rgba('+ this.state.cR +','+ this.state.cG+','+this.state.cB+',1)',
              opacity: 1}}/>
```

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.0

**Comment by andrewimm** [comment]
Good catch. Made a fix, landing soon
