### ISSUE TITLE
Custom Overlay with custom buttons

### ISSUE THREAD

**Issue by dijana-sagit** [facebook/react-360#507]
Hi,
There is, by default, Overlay that contains Compass and View in VR functions. I can change that by passing my own Overlay in customOverlay property in ReactInstance, as long as it implements OverlayInterface. But in this case, I wasn't able to figure out how to pass a callback and register it on my custom button. To be precise, I want to have environmental audio controls on my custom overlay.

The second approach was to simply use a native module DOM overlay. In this case, I was able to register the callback on the button within the DOM overlay, but then I get an error:

`The callback addVolumeCallback() exists in module GlassOverlayModule, but only one callback may be registered to a function in a native module.`

This is how my module looks like:

```
export default class GlassOverlayModule extends Module {
    constructor(ctx, overlayContainer) {
        super('GlassOverlayModule');
        this._volumeCallback= null;
        this._overlayContainer = overlayContainer;
        this._ctx = ctx;
        this._mute = this.mute.bind(this);
    }

    addVolumeCallback(volumeCallback) {
        this._volumeCallback = volumeCallback;
    }

    mute(vol) {
        if (this._ctx) {
            this._ctx.invokeCallback(this._volumeCallback, [vol]);
        }
    }

   openOverlay() {
        ReactDOM.render(
            <div style={WRAPPER_STYLES}>
                <VolumeButton buttonStyle={VOLUME_STYLES}  callback={this._mute}/>
...
```
I pass the callback through `addVolumeCallback` in index.js and it looks like:

`NativeModules.GlassOverlayModule.addVolumeCallback(this.handleEnvironmental);`
where:

```
handleEnvironmental(value) {
    const { AudioModule } = NativeModules;
    AudioModule.setEnvironmentalParams({muted: value});
  };
```
I suspect that I can't call AudioModule like this. I would appreciate any input.

Thanks,
Dijana

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.0
* Operating System: Windows
* Browser: Firefox
* VR Device: Out of VR

**Comment by andrewimm** [comment]
When a callback is passed from React to the runtime, it can only be called once.

If you want to trigger an effect multiple times from the runtime back to React, you will need to send events instead using RCTDeviceEventEmitter. Look at the code for ControllerInfo to see how controller connect / disconnect events are sent

**Comment by dijana-sagit** [comment]
Oh, this is great! Thank you!
