### ISSUE TITLE
Environmental audio potential issue

### ISSUE THREAD

**Issue by dijana-sagit** [facebook/react-360#509]
Hi,
I think there's a bug with environmental and spatial audio.

### Description
According to the documentation, there are three functions that deal with the environmental audio: `playEnvironmental`, `stopEnvironmental` and `setEnvironmentalParams`.

Bug
When I set an environmental audio initially, it partially works. It will load and play the audio, but the params _muted_, _volume_ and _loop_ seem like don't have any effect. Stop and setEnvironmentalParams seem like they don't have any effect. If I have an audio playing, and I call playEnvironmental for another audio, it will play both at the same time. Later I realized that the positional audio has the same problem.

### Reproduction

I have a glass overlay module from which I trigger mute toggle for environmental audio.
```
constructor(ctx, overlayContainer) {
        super('GlassOverlayModule');
        this._overlayContainer = overlayContainer;
        this._ctx = ctx;
        this.environmentalOnOff = this.environmentalOnOff.bind(this);
    }

    environmentalOnOff(mute) {
        if (this._ctx) {
            this._ctx.callFunction('RCTDeviceEventEmitter', 'emit', ['mutetoggle',mute]);
        }
    }
```
On react side, I have this:

```
constructor() {
        super();

        RCTDeviceEventEmitter.addListener('mutetoggle', this._onMuteToggle.bind(this));
    }

    _onMuteToggle(mute) {
        const { AudioModule } = NativeModules;
        let opts = {
            loop: false,
            muted: mute,
            volume: mute?0:0.5, 
            fadeTime: 500
        };
        AudioModule.setEnvironmentalParams(opts); // this doesn't have any effect, although the event is triggered
    };
```

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.0
* Operating System: Windows
* Browser: Chrome and Firefox
* VR Device: Out of VR

**Comment by dijana-sagit** [comment]
My apologies. It was my typo in coding. The audio works fine.

Regards,
Dijana

**Comment by dijana-sagit** [comment]
Hi, just to follow up on my previous inquiry. The reason I got this weird behaviour in the first place is that I mistakenly rendered the same component (which had the listener attached) on two different surfaces, which is ok according to the documentation. When I was going through logs, seems like _AudioModule_ and _VideoModule_ were loaded twice, and I could hear double sound in the environmental background, and consequently, _stopEnviromental_ was not working as expected. If needed I have the code to reproduce the error if this is an error.

**Comment by andrewimm** [comment]
Even if loaded twice, there is only one single instance of AudioModule and VideoModule in the actual runtime. This does sound like an odd bug, can you provide code that reproduces this?

**Comment by dijana-sagit** [comment]
Hi,

Please take a look at [https://github.com/dijana-sagit/AudioBugTest360/tree/master](https://github.com/dijana-sagit/AudioBugTest360/tree/master).

Regards,
Dijana

**Comment by Rhut-virani** [comment]
so I have a similar issue 
AudioModule.stopEnvironmental(); doesn't stop the audio.

also along with stop , there is a backgroundvideo  playback initiation which should itself stop the audio from playing but it doesn't.

**Comment by andrewimm** [comment]
@dijana-sagit Thanks! This helped me pinpoint a bug that occurs when you load two versions of the same environmental audio at the same time.

@Rhut-virani playing background video shouldn't stop background audio, that's not claimed anywhere in the documentation. Only playing a new environmental audio, or calling `stopEnvironmental()` should stop the old one. I'm currently running my local test suite off of the latest master, and `stopEnvironmental()` works as intended (other than the bug above). Can you provide an example that demonstrates the issue you're seeing?

**Comment by Rhut-virani** [comment]
My index.js has audio playing on render 

But one of my  component which is triggered on an if condition has a stopEnvironmental() and a setBackgroundVideo().

But still the  mp3 audio plays in the background and video plays without audio.

Also i am rendering only one component at a time so this shoild stop it but it doesnt seem to work or i am doing something wrong.
Documentation are not clear.
