### ISSUE TITLE
Unable to setup hotreload on React 360

### ISSUE THREAD

**Issue by jerichozis** [facebook/react-360#510]
There is no such information in documentation of React 360 and previous behaviors of react VR not working in React 360.

**Comment by amitrajput1992** [comment]
apparently, the ability to attach HMR is removed from the code. 
I attached it manually using this logic:
```
const bundleURL = new URL(bundle);
    console.warn(`HotReload on ${bundle}`);
    r360.runtime.context.callFunction('HMRClient', 'enable', [
      'vr',
      bundleURL.pathname.toString().substr(1),
      bundleURL.hostname,
      bundleURL.port,
    ]);
```

This is the same code taken from react-vr's ReactNativeContext
