### ISSUE TITLE
How to embed 2d Youtube Videos

### ISSUE THREAD

**Issue by Rhut-virani** [facebook/react-360#513]
### Description

How to embed youtube Videos inside a VR surface?  I think WebView is not working and Video component doesnt take iframe as source right?

#### Expected behavior
want  Youtube videos inside a View tag

* Operating System: [ Windows]
* Browser: [Chrome,]

**Comment by andrewimm** [comment]
Embedding youtube videos and iframes is not possible. This is not a limitation of React 360, but of all web browsers. We can only draw things that can be drawn to a <canvas> element – if it were possible, we would absolutely support this!
