### ISSUE TITLE
Ability to set cursor position to "Always Visible"

### ISSUE THREAD

**Issue by ryanf12** [facebook/react-360#515]
--- Delete everything above this line before submitting your issue ---

### Description

Is this a Bug or a Feature Request?

Feature Request. 

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

When using VR devices in “VR Mode” the white dot cursor is not visible unless the cursor is over a surface. 

This is problematic because when the cursor is not visible users cannot see where they are clicking and it makes for a challenging (and somewhat unusable) end-user experience.  

To reproduce the issue, initialize a project without a surface, and place your app in a center location.  Import some 3d obj files and mount them.  Put on your Oculus Go, grab your remote, open your project in the Oculus Browser, and click on "View in VR".  The visibility of the cursor will be hidden, however, you will still have the ability to interact with VrButtons (onClick/onEnter/onExit events do work).  

		function init(bundle, parent, options = {}) {  

		const r360 = new ReactInstance(bundle, parent,  {
		fullScreen: true,
		cursorVisibility: "visible", <-- this doesn't seem to work 
		...options,
		}); 

		r360.renderToLocation(
			r360.createRoot('App'),
			new Location([0, 0, 0]),
		  );`

`		<View key={index}>
		
			<VrButton onClick={this.clickActions.bind(this, current[index].targetState)}   }>
						<Entity
						 antialias={true} 
					source={{obj: "static_assets/"+current[index].imgSrc+".obj",  mtl:'static_assets/'+current[index].imgSrc+'.mtl',}}
					style={{transform: [{rotateY: current[index].rotateY}, {rotateX: current[index].rotateX}, {rotateZ: current[index].rotateZ}]}
				}	
        />
			</VrButton>
		</View>`

![cursor](https://user-images.githubusercontent.com/38990999/40935425-1b845dbe-6806-11e8-864c-2f5e5855fb77.png)

You can make the white dot cursor visible by placing the default cylinder surface in your environment.  

A consequence of placing the cylinder surface in the environment is that if you have a <VrButton> that contains a 3D object mounted to a location beyond the radius of the cylinder, the cylinder will ‘block’ the clickability of the VrButton and users will be unable to interact with the button.  

![unclickable](https://user-images.githubusercontent.com/38990999/40932543-b1757cfe-67fc-11e8-9954-f7968b764877.png)

You can _kind of_ solve this by scaling down your entire environment down to fit within the 4m sphere, however, the perspective doesn't quite look right that way and that's quite a workaround just to enable cursor visibility.  

• In the example image above, if you place a <VrButton> on any of the gray areas of the cube, they will be unclickable (the click event will register on the cylinder) and the cursor will be invisible.  
• Consequently, if you remove the cylinder surface altogether, there will be no visible cursor at all.  

### Solution

The docs say “A Cylinder Surface takes your 2D content and projects it onto the inside of a cylinder with a 4 meter radius.”  Would It would be useful to have the ability to make the scale of the default cylinder surface larger than the environment – so that the cursor is both **visible** and **clickable**.  

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

Cursor visibility should be enabled by default on VR devices.  Most people are going to want to see what they are clicking on.  

### Additional Information

* 'react-360' package version: 1.0.0
* 'react-360-web' package version: 1.0.1
* Operating System: Windows 
* Browser:  Oculus Browser
* VR Device: Oculus Go/GearVR

**Comment by andrewimm** [comment]
You can make the cursor always visible with the following:

```
r360.compositor.setCursorVisibility('visible');
```
The default value is `'auto'`, which relies on being over a surface.

Our cursor behavior is the exact same as what you see on Oculus's first-party apps. If you put on the Go, you'll only see your cursor if it's on a cylinder surface.

**Comment by andrewimm** [comment]
Also, to clarify, the cursor is visible in two scenarios in the default "auto" mode:

1) the cursor is over a surface
2) the cursor is over any object that has an onEnter/onExit/onInput listener

This covers both the 2D surface UI case (which we highly recommend everyone adopts) and the more classic 3D-floating-in-space case.

**Comment by ryanf12** [comment]
I do appreciate you looking into this. 

    r360.compositor.setCursorVisibility('visible');
    console.log(r360.compositor._cursorVisibility)

correctly returns:  

    visible

Unfortunately, when I select the "View in VR" button in the Oculus Go Browser the visibility of the white dot cursor is still hidden even with "_cursorVisibility:"visible" set.  

I'd prefer to use surfaces in this instance.  I was thinking of making a cube consisting of six (possibly more if tiled) surfaces that would resize proportionately as users move around to different areas of the scene.  

All of the examples I've looked at have the surface resizing in the client.js runtime before or immediately after init().  I've found that if you change the height/width from the stylesheet of the View wrapper that only crops surfaces without actually resizing and rerendering them.  

Is there currently any way to call, resize, and render a surface from _within_ React (not in client.js)?

**Comment by andrewimm** [comment]
I will attempt to reproduce your issue. Walking through the code, the cursor should definitely remain visible – my bet is that it might be setting the cursor depth improperly, that bit of code is currently in flux as we add a bunch of perf improvements to surface rendering.

As for the rest, have a look at #482 
The brief answer is today, you can roll your own. We are currently working on extending this functionality, but this is one of the APIs we share across Web (open source) as well as Mobile and PC (Oculus Internal). As such, we need to develop the APIs to work across all platform use cases. We can't just ship stuff to one platform and risk forking code again.
