### ISSUE TITLE
Strange calculation of width and height in QuadPanel

### ISSUE THREAD

**Issue by seb0zz** [facebook/react-360#517]
### Description

There seems to be an issue with the calculation of the width and height of the QuadPanel. The following formula is used e.g. for the width:

```
const halfWidth = this.props._layerDistance * (Math.PI * value.width / this.props._layerDensity);
```

So let's assume we have the following values:

```
this.props._layerDistance = 4
Math.PI = 3.1415... 
value.width = 1024
this.props._layerDensity = 4680 (default)
```

This leads to the result of ~ 2.74

#### Expected behavior

The correct width and height gets calculated.

#### Actual behavior

The resulting QuadPanel is extremely small.

### Reproduction

Can always be reproduced when using a QuadPanel.

```jsx
<QuadPanel layer={{ distance: 4, width: 1024, height: 720 }}>
  <View style={{
    width: 1024,
    height: 720,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
  }}>
    <Image 
      source={{ uri: sampleImageUri }}
      style={{
        width: 290,
        height: 290,
        backgroundColor: 'blue',
      }} 
    />
  </View>
</QuadPanel>
```

### Additional Information

* 'react-360' package version: 1.0.0
* 'react-360-web' package version: 1.0.1
* Operating System: MacOS
* Browser: Chrome
* VR Device: Out of VR

**Comment by seb0zz** [comment]
Ok, good to know that I should better use Surfaces instead of QuadPanel. Thanks for that!

Anyway I don't really understand the calculation. If I want a panel to have a width of 1024 pixels. And my density is 4680 pixels. I would expect that my panel covers 1024 / 4680 so ~ 22 % of the full cylinder view 🤔

**Comment by andrewimm** [comment]
It does. With a radius of 4m, the cylinder surface has a total circumference of 8π meters. ~22% of 8π is the 5.499m number I quoted above

Perhaps the confusion comes from the fact that a flat surface has the same physical dimensions as the cylinder equivalent, but has been unrolled into a plane?

**Comment by seb0zz** [comment]
Ok now I get what you mean. The calculation makes sense. Then it seems that the QuadPanel uses the 5.499m not as meters but as pixels.
