### ISSUE TITLE
How to access an onEnded event in VideoModule

### ISSUE THREAD

**Issue by ansible-comme** [facebook/react-360#518]
### Description
Hi,
I'm using the 
`VideoModule.createPlayer('myplayer') `
to set as background video with 
`Environment.setBackgroundVideo('myplayer');`

Is there a way to access an onEnded event in index.js for the currently playing 'myplayer' src?

### Solution

Any suggestions welcome

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.1
* Operating System: n/a
* Browser: n/a
* VR Device: n/a

**Comment by fanggu** [comment]
I don't think it can be accessed from react side. 

If you look into the VideoModule, it actually uses createPlayer() from VideoPlayerManager to create a BrowserVideoPlayer, then add it to the VideoPlayerManager list, but VideoModule doesn't provide a method to retrieve the player or add event listener to it.  

My solution is to create a video player from runtime (client.js) as described in the [documentation](https://facebook.github.io/react-360/docs/photos-and-videos.html), then add event listener to the video element. However, I only use the events to track the video status and usage, so it doesn't communicate with react side.

**in client.js**
```
const bgVideoPlayer = r360.compositor.createVideoPlayer('bgVideoPlayer');

const videoEventhandle = (e) => {
    console.log('------------Video Event----------\n', e);
}

bgVideoPlayer._element.addEventListener('ended', videoEventhandle, true);
```

**Comment by ansible-comme** [comment]
Hi @fanggu thanks a lot for this, although I do need to access in react unfortunately. 

Thought I may be able to pass as callback with [Native Modules](https://facebook.github.io/react-360/docs/native-modules.html), but not had any luck getting that to work.

So, Feature Request please.

#### Expected behavior
Ability to access 360 video events in index.js to perform function / state change 
#### Actual behavior
Not currently available?

**Comment by ansible-comme** [comment]
Hi,
I've managed to get this working for eventListening in React side using Native Modules.

**client.js**

```
player = r360.compositor.createVideoPlayer('myplayer');

class EventModule extends Module {
  constructor(ctx) {
    super('EventModule');
    this._rnctx = ctx;
  }

setEvent(eventType, cb) {
    player._element.addEventListener(eventType, eventFired => {
      eventFired = true
      this._rnctx.invokeCallback(cb, [eventFired])
    });
  }
}

//add context ref to nativeModules in init
nativeModules: [
      ctx => new EventModule(ctx),
    ]
```

**index.js**

```
const EventModule = NativeModules.EventModule;

componentDidMount() {
  EventModule.setEvent("eventType", eventFired => {
    console.log(eventFired);
    this.setState({eventType: eventFired});
  })
}
```

Native Module returns true when event has fired.

```
render() {
    let eventType = this.state.eventType;

    return (
      eventType ? ( 
//do stuff
)
```

**Comment by diogofgr** [comment]
@ansible-comme after following your code I got it to work but it only plays once. The next time it gives the error:
```
The callback setEvent() exists in module EventModule, but only one callback may be registered to a function in a native module.
```
Did you get this error? How did you fix it?

**Comment by ansible-comme** [comment]
@diogofgr  
Yeh sorry I had the same problem, so needed to initialise multiple players and add unique listeners. 

eg: 

```
  player = r360.compositor.createVideoPlayer('myplayer');
  playerB = r360.compositor.createVideoPlayer('myplayerB');
  player.setSource("firstUrl");
  playerB.setSource("secondURL");
  player.setMuted(false);
  playerB.setMuted(false);
```

```
  setEvent(eventType, cb) {
    player._element.addEventListener(eventType, eventFired => {
      eventFired = true
      this._rnctx.invokeCallback(cb, [eventFired])
    });
  }
  setEventB(eventType, cb) {
    playerB._element.addEventListener(eventType, eventFired => {
      eventFired = true
      this._rnctx.invokeCallback(cb, [eventFired])
    });
  }
```
```
componentDidMount() {
    EventModule.setEvent("ended", eventFired => {
    this.setState({firstVid: eventFired});
    // alternatively play alt vid on end.
      Environment.setBackgroundVideo('myplayerB');
      VideoModule.resume('myplayerB');

  })
    EventModule.setEventB("ended", eventFired => {
    this.setState({secondVid: eventFired});
})
}
```

I appreciate it isn't ideal - really, we need some dev to expose video events (like old ReactVR)

**Comment by acherkashin** [comment]
@ansible-comme, @diogofgr  Try to use `addListener` method instead of `addEventListener`.
If you look at `VideoModule.js` then you will see that `VideoPlayerInstance` has addListener method.

![image](https://user-images.githubusercontent.com/9947582/57586648-6ca9df80-7501-11e9-8b66-35228537aaaa.png)

So next code works well for me in react side.


```
this.player = VideoModule.createPlayer('BackgroundPlayer');
this.player.addListener('onVideoStatusChanged', (event) => {
                if (event.status === 'finished') {
                    this.player.destroy();
                    this.player = null;
             }
});
```

### Additional information:
"react": "16.3.2",
"react-native": "~0.55.4",
"three": "^0.87.0",
"react-360": "~1.1.0",
"react-360-web": "~1.1.0",

**Comment by ansible-comme** [comment]
Hi @acherkashin 

Thanks - events have been added since the original issue.

`addEventListener(event: string, listener: VideoEventListener)` now detailed in docs:
https://facebook.github.io/react-360/docs/photos-and-videos.html#from-react-1

closing this issue now.
