### ISSUE TITLE
mountToLocation is not a function

### ISSUE THREAD

**Issue by DevHominid** [facebook/react-360#519]
### Description

Bug / documentation error:

When migrating from `react-vr` to `react-360` by following the documentation outlined at https://facebook.github.io/react-360/docs/from-react-vr.html

Specifically here:

```
r360.mountToLocation(
  r360.createRoot('MyLegacyApp'),
  r360.getDefaultLocation(),
);
```

I run into the following error: "mountToLocation is not a function"

#### Expected behavior

r360.mountToLocation is a function

#### Actual behavior

r360.mountToLocation is not a function, throws error

### Solution

"mountToLocation" should be replaced with "renderToLocation"

### Additional Information

* 'react-360' package version: [react-360@1.0.0 ]
* 'react-360-web' package version: [react-360-web@1.0.1]
* Operating System: [MacOS]
* Browser: [Chrome]
* VR Device: [Out of VR ]

**Comment by andrewimm** [comment]
Fixed.
