### ISSUE TITLE
possible AudioContext bug in IE11

### ISSUE THREAD

**Issue by DevHominid** [facebook/react-360#520]
### Description

Bug:

react-360 app hosted on server works on all browsers except for IE11, where the following error is displayed:

`SCRIPT445: Object doesn't support this action`

![4f50b63c](https://user-images.githubusercontent.com/26509901/41247333-ef1a50e8-6d6a-11e8-87c0-ad840a4f2b0c.PNG)

Looks like it might be related to this issue that was patched for safari? https://github.com/facebook/react-360/issues/486

### Additional Information

* 'react-360' package version: [react-360@1.0.0]
* 'react-360-web' package version: [react-360-web@1.0.1]
* Operating System: [Linux]
* Browser: [IE11]
* VR Device: [Out of VR ]

**Comment by andrewimm** [comment]
Sorry, React 360 does not support IE11. We don't have the resources to do so.

**Comment by DevHominid** [comment]
Thought this might be the case! Thanks for the prompt response.
