### ISSUE TITLE
Build failed - unexpected token in bundle.js

### ISSUE THREAD

**Issue by cjdaniel-scu** [facebook/react-360#521]
### Description
SyntaxError: Unexpected token ) \node_modules\react-360\scripts\bundle.js:47

#### Actual behavior
C:\xxx\node_modules\react-360\scripts\bundle.js:47
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@0.0.1 bundle: `node node_modules/react-360/scripts/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@0.0.1 bundle script
### Reproduction

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

Ran fresh creation of boilerplate
$ react-360 init MY_Project

Verified creation of output in browser.
$ cd My_Project
$ npm run bundle

An example of your code that reliably reproduces the issue is ideal.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-360' package version: `-- react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.1
* Operating System: Windows
* Browser:  Chrome, FF
* VR Device: NA

**Comment by andrewimm** [comment]
What version of Node.js are you using?

**Comment by cjdaniel-scu** [comment]
v6.9.5

**Comment by cjdaniel-scu** [comment]
Took the hint, updated Node to one recommended - 8.11.2 - I think it was set to 6.9.5 for some reason for reactvr.
