### ISSUE TITLE
Plan to support WebXR

### ISSUE THREAD

**Issue by thienta25** [facebook/react-360#526]
### Description

Is this a Bug or a Feature Request?
This is a Feature Request. 
Many thanks for your contribute to VR community. 

- How do you think about WebXR? 

- Do you support WebXR in future?

**Comment by andrewimm** [comment]
Yes, we fully intend to support WebXR. It is a great step forward for the API, and simplifies a lot of the internals we have needed to implement for concepts like magic-window effects on 2D phones, or normalized input across a range of devices.

Despite what it may seem from browser vendors shipping early features, the spec is not yet finalized, and we do not plan to start building on top of it until it has been finalized.

**Comment by thienta25** [comment]
Oh, that sounds great. Thanks you and your team again.
