### ISSUE TITLE
Module not found: Error: Can't resolve 'View' in 'E:\project\react-electron\node_modules\react-360\Libraries'

### ISSUE THREAD

**Issue by sunhoudong** [facebook/react-360#538]
We use GitHub Issues for bugs and feature requests

--- Delete everything above this line before submitting your issue ---

### Description

Is this a Bug or a Feature Request?
For a Bug please explain below what you did, what you expected to happen, and what actually happens.

### Reproduction

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

An example of your code that reliably reproduces the issue is ideal.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-360' package version: [FILL THIS OUT: get this by running `npm list react-360`]
* 'react-360-web' package version: [FILL THIS OUT: get this by running `npm list react-360-web`]
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]
* Browser: [FILL THIS OUT: Oculus Browser, Chrome, Edge, Safari? Which version?]
* VR Device: [FILL THIS OUT: In or Out of VR? Headset? ]

**Comment by andrewimm** [comment]
Please provide more information on what causes your issue. We provide a template, so that you can give the information we need to track down the cause.

With just an error message, I cannot solve this.

**Comment by sunhoudong** [comment]
In other words, if I want to use react-360, I have to use react-360-cli to create the project, because only use it to download the react-360 related dependencies, right?

**Comment by andrewimm** [comment]
You don't have to use the CLI, but your projects won't work unless you have all the working files. The same can be said for React Native, and many other projects. The CLI is simply a helper to generate the necessary files.

I am suggesting that you can create a new project with the CLI and copy over all the necessary files to your existing directory, if you don't want to start a new project.

**Comment by sunhoudong** [comment]
OK,thank you!
