### ISSUE TITLE
registerTextureSource not found

### ISSUE THREAD

**Issue by 01binary** [facebook/react-360#540]
### Description

Unable to follow CustomTexture example because registerTextureSource API is missing on React 360 Instance. The older example got a ReactNative context which does still have this function, but there is no way I could find to get this context, all I have is a React 360 instance.

#### Expected behavior

r360.registerTextureSource is a function as shown in CustomTexture example

#### Actual behavior

r360.registerTextureSource is undefined

### Reproduction

Implement client.js for CustomTexture sample using the current version of React 360 where initializing it gives you a react 360 instance instead of the react native context. The instance does not provide a way to get the context or to call registerTextureSource

### Additional Information

* 'react-360' package version: 1
* 'react-360-web' package version: 1
* Operating System: Win10
* Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* VR Device: N/A

**Comment by andrewimm** [comment]
Legacy samples should not be expected to work. They should probably be deleted from this repo, if not upgrade-able.

The method in question is accessible at `r360.runtime.context.registerTextureSource`. We can move it up to the top-level ReactInstance, happy to accept PRs

**Comment by 01binary** [comment]
Perhaps we can re-frame this issue. Are custom (dynamic) textures still supported? For example, where the texture is an HTML5 canvas, just like in that sample. If they are still supported, do you recommend a pull request to update the public/website documentation for react 360?

I agree that:
* Old samples are not supposed to work
* We don't necessarily need a sample just to learn about dynamic textures

The real issue is that if there is no sample and no documentation, then there is a gap.

**Comment by andrewimm** [comment]
Yes, it is supported, at the method I just described.

There's a bunch of functionality that still exists in some form, but may or may not be deprecated in the future. If it's documented at https://facebook.github.io/react-360/docs/setup.html, it works as described. If not, it may change in the future.

**Comment by 01binary** [comment]
I didn't realize you were trying to avoid creating new help topics to minimize churn. This issue thread should be enough then for anyone else to find a solution.
