### ISSUE TITLE
Missing VR Support for Daydream Devices

### ISSUE THREAD

**Issue by DWishR** [facebook/react-360#542]
### Description
Daydream devices aren't presented with the option to enter Virtual Reality. I've verified that other WebVR experiences function via Chrome on devices with Daydream correctly configured. It's unclear why these devices aren't supported by React 360.

#### Expected behavior
1. "View in VR" button appears
2. Pressing button initiates WebVR experience

#### Actual behavior
1. "View in VR button" is absent

### Reproduction
1. Visit https://facebook.github.io/react-360/
2. Scroll down until "Welcome to React 360" canvas is fully visible
3. Note presence/absence of "View in VR" button
(I've also tested by utilizing `react-360 init hello` and pointing device's browser at resulting server)

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.2
* Operating System: Android
* Browser: Chrome 67.0.3396.87, Samsung Browser 7.2.10.33, Samsung Browser Beta 7.4.00.69
* VR Device: Google Pixel (Daydream View), Samsung Galaxy S9+ (Daydream View), Lenovo Mirage Solo

**Comment by andrewimm** [comment]
Are you sure you have WebVR enabled on these devices? I'm seeing no issues with the link you provided, testing both a Pixel 2 and a Mirage Solo

**Comment by DWishR** [comment]
You know what, you caused me to double-check and I discovered [this](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/available-trials.md) and [this](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md).

After enabling the flag according to [these instructions](https://webvr.rocks/chrome_for_android) it started working. Apologies, I had no idea that was a thing. I merely noticed other sites with functioning WebVR content while the react-360 page did not function.

You might consider getting a token for facebook.github.io as a trusted origin with regards to WebVR so that the first example people come across works out of the box.

**Comment by andrewimm** [comment]
The trial ends on Sept 11, it's really not worth getting an origin trial token at this point.
