### ISSUE TITLE
Respect React `ref` pattern for three.js Objects.

### ISSUE THREAD

**Issue by Marviel** [facebook/react-360#543]
### Description
Feature Request

### Expected behavior
Given a simple react Component that, simplified to the relevant details, looks like:
```
...
constructor(props){
  super(props);
  this.myRef = React.createRef();
}
...
render(){
  <Scene>
    <View>
      ...
      <Sphere ... 
         ref={this.myRef}>
      ...
    </View>
  </Scene>
}

```

Would allow access of the base three.js object via `this.myRef.current`, as it is done in the [React Ref Documentation](https://reactjs.org/docs/refs-and-the-dom.html)

### Actual behavior
`this.myRef.current` does not contain a reference to the current three.js object.

### Example Use Cases
- Getting bounding box of a part given its transforms.
- Performing a raytracing operation on a part, unrelated to a mouse movement.
- Calculating the intersection/non-intersection of two parts given their transforms.
- Getting the triangle-count, vertex-count, and other properties of a model.

### Solution
Make React-360 component refs operate more similarly to React DOM components, in that getting the `ref` of a component will get its three.js object, in addition to the other things that are returned.

**Comment by andrewimm** [comment]
Our behavior is the same as React Native here. We cannot access the Three object via ref for a number of reasons:

1) Today, the React code runs in a different context for performance reasons. It's not possible to transfer an actual JS reference over to a web worker – only JSON-stringify-able objects. There's no way for your React code to access the backing Three object directly
2) It doesn't work across platforms. React 360 has the same APIs as our internal native implementation, React VR. We need to be able to maintain behavior in a way that React code runs the same on each platform – if you're passing something that's platform specific, that breaks. If we want to bring React VR to external developers one day, changes like this would prevent that.
3) Raw access to a Three.js object being managed by React can be dangerous. The code that manages a SphereGeometry with a React component makes some assumptions about that geometry. With absolute access, changes could be made that break those assumptions.

**Comment by Marviel** [comment]
@andrewimm thanks for the quick reply! Appreciate the detailed response
