### ISSUE TITLE
Porting the Tour Sample from React VR to React 360

### ISSUE THREAD

**Issue by KingTomaHawk** [facebook/react-360#547]
### Description

Need help "porting" Tour Sample from React VR to React 360.

#### Expected behavior

Functional Sample

#### Actual behavior

I can only see a small area of my 360 Picture:
![demo](https://user-images.githubusercontent.com/36895999/43305259-612994f2-9177-11e8-8eed-6b9b7cf97728.PNG)

### Reproduction

- import all packages from react-360 instead of react vr in all project files
- remove background-color option from Panos ( because it's not supported anymore)
- uncommented all sound features (because of some errors)

changed client.js to:
``` import {ReactInstance,  Location, Surface} from 'react-360-web';

function init(bundle, parent, options = {}) {
  const r360 = new ReactInstance(bundle, parent, {
    fullScreen: true,
    ...options,
  });
  
  
  
	r360.renderToSurface(
      r360.createRoot("TourSample", { /* initial props */ }),
      r360.getDefaultSurface()
   );
  
}
  
window.React360 = {init};
```

Changed index.html to:
```
<html>
  <head>
    <title>ReactVR: Tour Sample</title>
    <style>body { margin: 0; }</style>
  <head>
  <body>
    <!-- When you're ready to deploy your app, update this line to point to your compiled client.bundle.js -->
    <script src="./client.bundle?platform=vr"></script>
    <script>
      React360.init(
        '../index.bundle?platform=vr&dev=true',
		document.body
      );
    </script>
  </body>
</html>
```

### Solution

/

### Additional Information

* 'react-360' package version: 1.0.0
* 'react-360-web' package version: 1.0.2
* Operating System: Windows
* Browser: Chrome, Firefox
* VR Device: Just black screen on Oculus Go

Edit: My first (real) bugreport on Github so forgive me any mistakes :)

**Comment by KingTomaHawk** [comment]
@karmaggyatso sadly no.

**Comment by karmaggyatso** [comment]
Hey @andrewimm, could you help us to resolve the above problem, please. Thank you.

**Comment by moroneyk** [comment]
Hi,

You might want to try rendering to a location instead of to a surface in your client.js file, it should solve the issue:


```
  r360.renderToLocation(
    r360.createRoot('TourSample', 
      { 
         /* initial props */
      }
    ),
    r360.getDefaultLocation()
  );
```

Check also that you are setting background panorama using the Environment module something like:

```
    Environment.setBackgroundImage(
          props.uri,
          {format: props.format} /* one of the new 3d formats */
    );
```

Let me know if this helps,
Kevin

**Comment by KingTomaHawk** [comment]
Hi Kevin,

sry I was on vacation. Changing from Surface to Location fixed the issue, but It was lagging. Removing the Sound Module from import, fixed that problem.

Thanks
