### ISSUE TITLE
[Question] Is it possible to change the wrapping of a texture on a mesh?

### ISSUE THREAD

**Issue by Fischaela** [facebook/react-360#55]
Hello :) The documentation says, that a texture can be used with a mesh, instead of a material:

```
<Mesh
  source={{mesh:'cube.obj', texture:'cube.jpg'}}
/>
```

I was wondering, if it is possible to change the wrapping of the texture. three.js e.g. has `wrapS` and `wrapT` properties for a texture with [three possible wrapping mode values](https://threejs.org/docs/?q=texture#Reference/Constants/Textures) (`THREE.RepeatWrapping`, `THREE.ClampToEdgeWrapping`, `THREE.MirroredRepeatWrapping`).

**Comment by amberroy** [comment]
Currently the default is ` THREE.ClampToEdgeWrapping` and there is no way to override it although we could add that as a property.  Which wrapping mode do you wish to use for your texture?

**Comment by Fischaela** [comment]
Thank you for your answer, @amberroy 
In general I need `THREE.RepeatWrapping` and `THREE.ClampToEdgeWrapping`.

Tbh, I think `THREE.ClampToEdgeWrapping` is not working as intended at the moment within my code. This is the `Mesh` with the texture:

```
<Mesh
        style={{
          transform: [
            {translate: [xOffset, 0.1, -0.5]},
            {scale: [imageWidth, imageWidth, 0.001]},
          ],
        }}
        source={{mesh:asset('cube_wall.obj'), texture:asset('IGtoGD_0.jpg'), lit: true}}/>
```

The texture is an Instagram photo, which is located in the `static_assets` folder. I attached a screenshot of the cube image with the incorrect rendered texture and the texture asset itself. I must be missing something else here.

<img width="768" alt="bildschirmfoto 2017-02-24 um 11 02 10" src="https://cloud.githubusercontent.com/assets/3409561/23299192/dcf16680-fa80-11e6-952f-cbe9f11b1705.png">

**Comment by exedriver** [comment]
Is this option (switch wrapping mode) planed for a future release? 

I currently have a box component where I want to put a texture on - and let it repeat instead of be stretched. The size of the box can be changed within my application, so a stretched texture doesn't work here. As I understood, this is currently not possible? From my point of view this should be a feature, because objects like boxes or cylinders are predestined to have dynamic dimensions.

**Comment by jgwinner** [comment]
Given three.js supports it, I think this would be a very valuable feature. It can be used at low memory cost to build large objects. Granted, repeating textures can look a little too regular but could still be useful to keep geometry down a bit.

Anyway, my vote would be yes, as an enhancement.

== John ==
