### ISSUE TITLE
running http://localhost:8081/index.html throw Apache Tomcat/8.0.41 -Error report

### ISSUE THREAD

**Issue by vijay-kumar-singh** [facebook/react-360#561]
Hi,
I am trying to run react360 hello world example.
I installed all required library but when i run 'npm start', application does not start and its throw 
Apache Tomcat/8.0.41 -Error report

HTTP Status 404 - /index.html

type Status report

message /index.html

description The requested resource is not available.
Apache Tomcat/8.0.41

Please suggest how to fix this and run application.

**Comment by kevinsimper** [comment]
@vijay-kumar-singh You have Tomcat running on the same port?

**Comment by andrewimm** [comment]
This is not a React 360 issue. Tomcat is unrelated to React 360's server, you have the service running elsewhere and interfering with the server.

You can change the port that React 360 uses with 
```
npm start -- --port NNNN
```
which will start the server on localhost:NNNN instead

**Comment by Jamesjaj** [comment]
Having some issue with my terminal , starting my new project but having issuing running the  

npm start 

keep telling me errors
