### ISSUE TITLE
Query on Dynamic Surfaces

### ISSUE THREAD

**Issue by moroneyk** [facebook/react-360#574]
I am trying to create a series of dynamically generated surfaces for displaying points of interest in a scene (a series of interconnected rooms, each room with its own Points of Interest). 
When the user changes room, the points of interest are regenerated and I want to update the contents and reposition the surfaces. At the moment I am just adding the POIs to a view in a CylindricalPanel, but depending if they are close to the edge of the cylinder the contents are truncated, I would like to start displaying them on a flat surface and position them using the Surface.setAngle(a, b). 

I saw in a previous post that the following approach was suggested (Issue #482):

_In index.js_
```
const {SurfaceModule} = NativeModules;

SurfaceModule.requestSurface().then(handle => {
  // handle is a unique string identifier for referencing a surface
  // Resize to 500x300px
  SurfaceModule.resize(handle, 500, 300);

  // Tell client.js to instantiate a new instance of <ReactRootName> on the new surface
  SurfaceModule.renderToSurface('ReactRootName', { /* initial props */ }, handle);

  // Later on, free up the surface again
  SurfaceModule.unmountComponentAtSurface(handle);
});
```

It was suggested to expose a method that updates a surface instance on the client side, I'm a bit lost on what this would look like on the client.js side. Is there any chance you could give an outline of how to go about exposing this from client.js? What would the function below look like? From what I can make out there is no way to access the r360 object, hence no way to call renderToSurface or createRoot?

`  SurfaceModule.renderToSurface('ReactRootName', { /* initial props */ }, handle);
`

**Comment by kNewbown** [comment]
I don't think this is what you asked, but thought I'd comment in case it was of use.
I rendered my POIs to location, rather than to surface, and it was very easy.

In _client.js_
```
r360.renderToLocation(
   r360.createRoot('ReactRootName'),
   new Location([0, 0, 0]),
)
```
Rendered my POIs in relation to that 0,0,0 location:
```
<View
   style={position}
>
   <VrButton>
      <Image
         source={{uri: `${this.props.icon}`}}
      />
   </VrButton>
</View>
```
Position was set on the view with:
```
const position = {
   position: 'absolute',
   transform: [
      {translateX: this.props.position.x},
      {translateY: this.props.position.y},
      {translateZ: this.props.position.z},
      {rotateX: this.props.position.rx},
      {rotateY: this.props.position.ry},
      {rotateZ: this.props.position.rz},
   ]
}
```
