### ISSUE TITLE
Video & Audio is not playing even initate over componentDidMount

### ISSUE THREAD

**Issue by tahabesthive** [facebook/react-360#581]
### Description

Video and Audio is playing is stable over Desktop and Browsers Auto,but its not working on Iphone and Mobile Device

#### Expected behavior
Video Should play with Audio

#### Actual behavior
Just React-360 Handler open video loaded with stop condition.

#### Actual Code
  componentDidMount = () => {
      VideoModule.createPlayer('myplayer');
      // Play a specific video
      VideoModule.play('myplayer', {
        loop: true,
        volume : 1,
        muted : false,
        source: {url: ('/static_assets/video.mp4')}, // provide the path to the video
      });
      VideoModule.setParams('myplayer', {
        volume: 1, // provide the path to the video
        muted: false, // optionally, supply the format of the video
      });
      Environment.setBackgroundVideo('myplayer');
      VideoModule.resume('myplayer');
  };

### Additional Information

* 'react-360' package version: [FILL THIS OUT: get this by running `npm list react-360`]
* 'react-360-web' package version: [FILL THIS OUT: get this by running `npm list react-360-web`]
* Operating System: [FILL THIS OUT: MacOS?]
* Browser: [FILL THIS OUT: Safari ]
* VR Device: [FILL THIS OUT: Iphone 6 ]

**Comment by larrylin28** [comment]
It's generally a security policy that a audio/unmuted video cannot be played without an user interaction. 
Same issue as https://github.com/facebook/react-360/issues/573
