### ISSUE TITLE
Billboarding does not work in VR Mode

### ISSUE THREAD

**Issue by moroneyk** [facebook/react-360#587]
### Billboarding does not work in VR Mode

Bug: when applying billboarding to a view, the billboarding works correct when not in VR, but once the user enters VR billboarding does not work correctly, it looks like the camera values used by the billboarding code in React360/OVRUI/UIView/UIView.js is not updating values correctly in VR mode. 

#### Expected behavior

Billboarding should work in VR and non-VR modes

#### Actual behavior

Billboarding only works in non-VR modes.

### Reproduction

set billboarding to on on any View. Observe that billboarding works correctly in non-VR mode, but stops working in VR mode.

```
<View
   billboarding={'on'}
   style={{
      layoutOrigin: [0.5, 0.5],
      position: 'absolute',
         transform: [
            { rotateY: rotationX },
            { rotateX: Y },
            { translate: [0, 0, -distanceToView] }
         ]
      }}
>

      Some content

</View>

```

### Solution

Validate the values used in the  `updateBillboard:` function in React360/OVRUI/UIView/UIView.js are received/updated correctly in VR mode. 

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.2
* Operating System: All
* Browser: All
* VR Device: All

**Comment by andrewimm** [comment]
Billboarding is no longer a supported feature. We may ship a bugfix to adjust this in 1.x.x, but you can expect this to go away in the future. In general, Views arbitrarily positioned in 3D space are deprecated in favor of Surfaces.

**Comment by moroneyk** [comment]
Thanks Andrew, I figured that was probably the case and have started migrating everything to a managed surface pool of reusable surfaces. 
Is there a roadmap for the upcoming changes/development with React-360 you could share to avoid going down any dead ends which may require redevelopment efforts in the short term?
