### ISSUE TITLE
Using Environment to setBackgroundVideo is not working and shows up a black screen.

### ISSUE THREAD

**Issue by hvardhan617** [facebook/react-360#596]
Sample Code used ;

  createVideo(){
      console.log("Creating Video:::::");
      VideoModule.createPlayer('myplayer');
      // Play a specific video
      VideoModule.play('myplayer', {
        source: {url: staticResourceURL('/static_assets/video.mp4')}, // provide the path to the video
        stereo: '2D', // optionally, supply the format of the video
      });
    }

Environment.setBackgroundVideo('myplayer');

This just shows a black screen and nothing else..Can somebody give me an example of how exactly to use it or a link to a sample project.?

**Comment by ansible-comme** [comment]
Hi, 

I'd take a look at this page for building a player, couple of options with video - available from React and Client.js w/examples:
https://facebook.github.io/react-360/docs/photos-and-videos.html

But this is probably what you're looking for (from link above):
```
import {Environment, NativeModules, staticResourceURL} from 'react-360';
const {VideoModule} = NativeModules;

// Create a player
VideoModule.createPlayer('myplayer');
// Play a specific video
VideoModule.play('myplayer', {
  source: {url: staticResourceURL('path/to/video.mp4')}, // provide the path to the video
  stereo: '3DTB', // optionally, supply the format of the video
});
// Display the video on the Environment
Environment.setBackgroundVideo('myplayer');
```
Worth noting from the docs:
> a Player must be set up before it can be set to the Environment. 

So, check your function `createVideo()` is being called before `Environment.setBackgroundVideo('myplayer')`? 

Also, not sure you need that function at all. You can create player and call `Environment.setBackgroundVideo('myplayer')`  at some point later when you're ready to set the video.

p.s missing your 'E' in Environment in the comment above (just in case pasted from your code!)....

**Comment by hvardhan617** [comment]
I have already tried what you have suggested,but none of them seem to work..it just shows up a black screen

**Comment by andrewimm** [comment]
Have you mounted any React surfaces? The renderer doesn't actually start drawing until you draw your first scene, or explicitly call `r360.start()`

**Comment by hvardhan617** [comment]
Yes,
I have a couple of surfaces and locations rendered onto the scene before calling the setBackgrounVideo function.
Please have a look at my client.js

// This file contains the boilerplate to execute your React app.
// If you want to modify your application's content, start in "index.js"

import {ReactInstance,Surface,Location} from 'react-360-web';

function init(bundle, parent, options = {}) {
  const r360 = new ReactInstance(bundle, parent, {
    // Add custom options here
    fullScreen: true,
    ...options,
  });

  // Render your app content to the default cylinder surface
//  r360.renderToSurface(
  //  r360.createRoot('HighRadiusVR', { /* initial props */ }),
    //r360.getDefaultSurface()
  //);


  const leftPanel = new Surface(300, 600, Surface.SurfaceShape.Flat);
  leftPanel.setAngle(-0.6, 0);
  r360.renderToSurface(
  r360.createRoot('HighRadiusVR'),
  leftPanel,
);

const rPanel = new Surface(300, 600, Surface.SurfaceShape.Flat);
rPanel.setAngle(0, 0);
r360.renderToSurface(
r360.createRoot('RotatingAnimation'),
rPanel,
);

const rightPanel = new Surface(300, 600, Surface.SurfaceShape.Flat);
rightPanel.setAngle(0.6, 0);
r360.renderToSurface(
r360.createRoot('MultipleTimingAnimation'),
rightPanel,
);

// Create a location two meters in front of the user, and one meter down
const location = new Location([0, -3, -8]);

// Render to this location
r360.renderToLocation(
  r360.createRoot('ImportModel'),
  location,
);

const player = r360.compositor.createVideoPlayer('myplayer');
// Instantiate the video, but do not play it yet
player.setSource('/static_assets/Vid1.mp4','2D');


// To play a video as your background, reference it by its unique id
r360.compositor.setBackgroundVideo('myplayer');

  // Load the initial environment
//r360.compositor.setBackground(r360.getAssetURL('360_world.jpg'));
}

window.React360 = {init};

**Comment by ansible-comme** [comment]
This is my working project, stripped back:

```
//client.js

import {ReactInstance} from 'react-360-web';

function init(bundle, parent, options = {}) {
  const r360 = new ReactInstance(bundle, parent, {
    fullScreen: true,
    ...options,
  });
  player = r360.compositor.createVideoPlayer('myplayer');
  player.setSource("yoururl");
  player.setMuted(false);
}

window.React360 = {init};

```

```
//index.js

import React from 'react';
import {
  Environment,
  NativeModules,
} from 'react-360';

const {VideoModule} = NativeModules;

export default class islandVR extends React.Component {
  constructor(){
      super();
      this.state={
        //
      };
    }

Environment.setBackgroundVideo('myplayer');
VideoModule.resume('myplayer');
      

  render() {
    return (
//
  )
  }
};


AppRegistry.registerComponent('VR', () => VR);

```

I've had a problem getting 5.2k videos from GoPro Fusion to play - had to render them down to 4k to get them playing in desktop (chrome) and export at 3840 x 2160 , rather than  4096 x 2098 to get them playing in Oculus Go browser.

**Comment by hvardhan617** [comment]
Thank you for the code.Finally i got it working after putting r360.start() in my client.js
