### ISSUE TITLE
Logo guidelines

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-360#602]
### Description

Request for information

### Additional Information

I found "https://facebook.github.io/react-360/img/logo.svg" but that seems to be the "React" logo, not just React 360. 

Is there an official logo and/or guidelines for proper use of it?

Thanks!

P.S. I don't mind putting together one, btw.

**Comment by andrewimm** [comment]
That is the official logo. Like React Native, we use the standard React logo with alternate coloring.

**Comment by jgwinner** [comment]
Ok. It doesn't have a background color though, nor the letters "React 360" which I added recently for a SIGGRAPH presentation. Just wanted to check if there was something else.

Thanks,

== John ==
