### ISSUE TITLE
Frame rate drops significantly when more than 4 Image projects are present in the View.

### ISSUE THREAD

**Issue by IMFIL** [facebook/react-360#603]
### Frame rate drops incredibly low when I include more than 4 images that are 1.9MB of size.

This is the Item Class:

`

     import React, { Component } from 'react';
     import {
      asset,
      View,
      Image
     } from 'react-360';

    const ItemIconWidth = 30;
    const ItemIconHeight = 30;

    class Item extends Component {

    constructor(props) {
     super(props);

     this.state = {
       x_position: 0,
       y_position: 0,
       imgSrc: "",
       recommendedItems: []
     };
    }

    componentDidMount() {
     this.setState(
       {
         x_position: this.props.x_position,
         y_position: this.props.y_position,
         imgSrc: this.props.imgSrc,
         recommendedItems: this.props.recommendedItems
       }
     )
    }

    render() {
     return (
      <View style={{width: ItemIconWidth, height: ItemIconHeight, transform: [{translate: 
       [this.state.x_position, this.state.y_position, 0]}]}}>
         <Image style={{width: ItemIconWidth, height: ItemIconHeight}} source={asset('itemSign.png')} 
          />
      </View>
     );
    }

    }

    export default Item;

`

Then the Item is called in a View in the index.js

The image:

![itemsign](https://user-images.githubusercontent.com/16093847/47249515-2c0e3b80-d3e2-11e8-85d4-cc3d444ee737.png)

Device being used is a Macbook pro, tested on Google Chrome.
Does anyone know why this is so.

**Comment by andrewimm** [comment]
Can you provide more information? Sample code, sample images? What device are you using?

Without our own use cases of React 360, we regularly have dozens of large images on the screen that run at full frame rate on Oculus Go.

**Comment by IMFIL** [comment]
Added more information to the initial comment ! I assumed that something was wrong on my side, but could not figure out what I was doing wrong. It was fixed when I reduced the size of the image to 4KB, instead of 1.9MB.
