### ISSUE TITLE
Question: why does X, Z rotation have distance, but rotation Y doesn't

### ISSUE THREAD

**Issue by zmax92** [facebook/react-360#608]
I have added object to my project, added rotation Y and rotation is in one spot around the axis
![rotatey](https://user-images.githubusercontent.com/12643259/47317821-c7a1e500-d64a-11e8-909c-d14c7e90ffec.gif)

but for rotation X is not rotation in one spot but it has some distance
![rotatex](https://user-images.githubusercontent.com/12643259/47317820-c7a1e500-d64a-11e8-8d67-34cebe4bfb11.gif)

same is for Z rotation
![rotatez](https://user-images.githubusercontent.com/12643259/47317822-c7a1e500-d64a-11e8-8e17-bb9b887cf579.gif)

Can somebody explain why is this happening, is something in my code, or is it react-360 thing and in that case is there a way to fix this?

index.js

    import React from 'react';
    import {
      AppRegistry,
      asset,
      Animated
    } from 'react-360';
    import Entity from 'Entity';

    const AnimatedEntity = Animated.createAnimatedComponent(Entity);

    export default class example extends React.Component {
      constructor() {
        super();        
        this.state = {
            xRotate: 0
        }
      }

      componentDidMount(){
        setInterval(() => {
            this.setState({
                xRotate: this.state.xRotate + 1
            });
        }, 50);
    }

      render() {
        const { xRotate } = this.state;
        return (
          <AnimatedEntity
            style={{transform: [{rotateX: xRotate}]}}
            source={{
                obj: asset('scrollObj/scroll.obj'),
                mtl: asset('scrollObj/scroll.mtl'),
            }}
          />
        );
      }
    };

    AppRegistry.registerComponent('example', () => example);

client.js

    import {ReactInstance, Location} from 'react-360-web';

    function init(bundle, parent, options = {}) {
      const r360 = new ReactInstance(bundle, parent, {
        // Add custom options here
        fullScreen: true,
        ...options,
      });

      r360.renderToLocation(
        r360.createRoot('example'),
        new Location([0, -1, -3], [0, 0, 0, 1])
      );

      // Load the initial environment
      r360.compositor.setBackground(r360.getAssetURL('360_world.jpg'));
    }

    window.React360 = {init};

**Comment by andrewimm** [comment]
This is not related to React 360, but your model.
Within the model, its faces are arranged around a local origin. When rotations are applied, they are applied to the entire model. If your model's components are not centered around its origin, they will move in space, since the origin is what is being rotate.
If you want rotations to apply to the center of your model, then its origin needs to be at its physical center.

**Comment by zmax92** [comment]
Thank you for the reply... after adjusting the model now it's working fine. Thanks
