### ISSUE TITLE
View transform in a 3D location does not work as expected

### ISSUE THREAD

**Issue by Manny-Mobfish** [facebook/react-360#612]
### Description
We use lon, lat & distance values to calculate the positions for "Hotspots". For this we use a 3d location. The positioning of Hotspots works and is correct as long as we use `<Plane>`. But if we try to create the same transformation on `<View>` the positions are not correct anymore.

Our 3d location:
`
r360.renderToLocation(
    r360.createRoot('sampleApp'),
    r360.getDefaultLocation()
);
`

the render() method of our index.js looks like this:
`
render() {
    const {activeScene} = this.state;

    let hotspotItems = null;

    if (activeScene) {
        hotspotItems = activeScene.hotspots.map((hotspot) =>
            <Hotspot key={uuidv4()} hotspot={hotspot} changeScene={this.changeActiveScene}/>
        );
    }

    return (
        <View style={{
            transform: [{translate: [0,0,0]}]
        }}>
            {hotspotItems}
        </View>
    );
}
`

And the Hotspot Component returns:
`function Hotspot({hotspot, changeScene}) {

    let hotspotPosition = calculateHotspotPosition(hotspot.marker.posLon,
        hotspot.marker.posLat,
        hotspot.marker.posDis);

    let hs;

    // Load a hotspot component depending on hotspot.type
    switch(hotspot.type) {
        case "mediaLink":
            hs = <SceneLinkHS hotspot={hotspot} changeScene={changeScene} />;
            break;
        default:
            hs = null;
    }

    return (
        <View style={{
            transform: [
                {translateX: hotspotPosition.transform.x},
                {translateY: hotspotPosition.transform.y},
                {translateZ: hotspotPosition.transform.z},
                {rotateY: hotspotPosition.rotate.y},
                {rotateX: hotspotPosition.rotate.x}
            ],
            width: 1,
            height: 1,
            backgroundColor: "rgba(0,0,0,0.8)",
            layoutOrigin: [0.5,0.5],
        }}
        >
            {/*{hs}*/}
        </View>
    );
}`

If we change in our Hotspot return the `<View>` to a `<Plane>` every single Hotspot has the correct position. 

#### Expected behavior
![expected](https://user-images.githubusercontent.com/43474780/47489000-daccd480-d845-11e8-9b92-27016aa6eda9.png)
Hotspots are correctly positioned according to the calculations. (In this screenshot we used `<Plane>`

#### Actual behavior
![actual](https://user-images.githubusercontent.com/43474780/47488991-d56f8a00-d845-11e8-8411-1c0990ad8eb9.png)
But if we use `<View>`, something magical happens.

### Solution

Should views in a 3D location not be positioned exactly like planes with x,y,z coordinates?

### Additional Information

* 'react-360' package version: react-360@1.0.0 
* 'react-360-web' package version: react-360-web@1.0.2 
* Operating System: MacOS
* Browser: Every Browser has the same result
* VR Device: InVR and !InVr

**Comment by Manny-Mobfish** [comment]
Just found out, that position: 'absoulte' on the `<View>` fixed the problem. But is this really the solution to use absolute positioning for each view?

**Comment by larrylin28** [comment]
@Manny-Mobfish Hi, so a clear explanation is, when React(yoga) doing layout, it by default uses `position='relative'`, which means it will layout the views relative to it's parent and sibling, `position='absoulte'` is the way to layout it independently from absolute position.
So yes, using absolute positioning on the views that you want to layout absolutely from their parent is the right solution

**Comment by sjmueller** [comment]
React Native uses Yoga, and has `transform: [{ translateY }, { translateX }]` in addition to `position: absolute`. Furthermore, iOS native has `CGAffineTransform(translationX:, y:)`, so there is definitely a need to manipulate these values even when `position: relative`, *especially* with animations. Example is fadeUp, slideDown etc.

That being said, is `position: absolute` the only option for pure Yoga layouts?
