### ISSUE TITLE
GuiSys.js -> _onPresentChange() throws TypeError

### ISSUE THREAD

**Issue by Manny-Mobfish** [facebook/react-360#614]
### Description

Bug Request:
react-360-web/js/OVRUI/UIView/GuiSys.js 
the method _onPresentChange(e) throws an error on VrMode switch.

![bildschirmfoto 2018-11-01 um 10 58 39](https://user-images.githubusercontent.com/43474780/47845383-25f66280-ddc5-11e8-86ff-09651a4e6da9.png)

This could be maybe a reason why, the inVr() function of the VrHeadModel not work as expected.

#### Expected behavior
use of the detail object:

```
_onPresentChange(e) {
	this.isVRPresenting = e.detail.display.isPresenting;
}
```

#### Actual behavior
```
_onPresentChange(e) {
	this.isVRPresenting = e.display.isPresenting;
}
```

### Reproduction
Open the dev tools in the browser of your choice and click the button "View in VR".

### Solution
A console.log of the e parameter shows that the display attribute is in the detail object.
![bildschirmfoto 2018-11-01 um 11 00 48](https://user-images.githubusercontent.com/43474780/47845619-cd739500-ddc5-11e8-9f14-b8e4199b59fa.png)

Changing the line:
```
this.isVRPresenting = e.display.isPresenting;
```

to

```
this.isVRPresenting = e.detail.display.isPresenting;
```

would solve the issue.

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.2 
* Operating System: MacOS
* Browser: Chrome 70.0.3538.77
* VR Device: Samsung Galaxy S7, Chrome Browser

**Comment by larrylin28** [comment]
This is already fixed on github: https://github.com/facebook/react-360/blob/master/React360/js/OVRUI/UIView/GuiSys.js#L704

Please use local change to fix that on your project, and next npm release will contain the fix.

**Comment by pinkytv** [comment]
The line you've marked is still e.display.isPresenting. Will you change it within the next release?

**Comment by larrylin28** [comment]
@pinkytv OK, so I misunderstood your description.  The current one (`e.display.isPresenting`) is the correct one, please refer to the latest WebVR APIs: 
https://developer.mozilla.org/en-US/docs/Web/API/VRDisplayEvent
Are you using an old browser?

**Comment by pinkytv** [comment]
Hey I'm using the latest version of [webvr-polyfill](https://github.com/immersive-web/webvr-polyfill), since [WebVr isn't supported](https://webvr.rocks/) on most common mobile browsers.

**Comment by larrylin28** [comment]
Then that is the issue of webvr-polyfill, as it's not following WebVR API, please report the issue there.
