### ISSUE TITLE
Help how to create smooth circle in surface

### ISSUE THREAD

**Issue by zero-xr** [facebook/react-360#616]
### Description
When use borderRadius 50% to create circle in surface. This circle is not smooth.
Can you instruction problem or other method to create circle? Thanks you.
![image](https://user-images.githubusercontent.com/40929675/47976886-64529100-e0e7-11e8-84fe-1e9a488c1e6a.png)

#### Expected behavior
Smooth circle in surface.

**Comment by larrylin28** [comment]
Hi, there're several ways:
1. You can use a round Image instead
2. When you creating the surface, you can use setDensity to use a higher density for the surface. (You need to increase the size of all of your views as well.
3. You can use "useNewViews" option to use the new view renderer

**Comment by zero-xr** [comment]
@larrylin28 thanks you. Will try your suggestion. :+1:
