### ISSUE TITLE
Moving camera in new react 360, not react VR

### ISSUE THREAD

**Issue by yerkejs** [facebook/react-360#618]
I wanted create website with new react 360. But I faced this problem. I searched answers but could not find. I want move my camera with keyboard. Help!

**Comment by andrewimm** [comment]
This has been covered in other issues. React 360 provides a pluggable interface called CameraController (https://github.com/facebook/react-360/tree/master/React360/js/Controls/CameraControllers) that has the opportunity to change the camera's rotation and position each frame. Your application's input controls are found at `r360.controls`.
If you want to move the camera with the keyboard, you should build a CameraController that updates the position based on keypresses. A CameraController must implement the following method:
```js
fillCameraProperties(
  position: [number, number, number],
  rotation: [number, number, number, number]
): boolean
```
Each frame, this method will be called. If you want to update the position, you should change the elements of the array passed to the first argument.

When your application initializes, you should remove the existing camera controllers (`r360.controls.clearCameraControllers`) and add your new one (`r360.controls.addCameraController(myKeyboardController)`)

**Comment by erkeElzhan** [comment]
it is really big actual question. It is always hard for beginners. @andrewimm  could you show little example. I mean can you make simlpe example and send source code.

**Comment by andrewimm** [comment]
GitHub issues are meant to be used for reporting bugs or requesting features. If you have questions about how to build something, a website like StackOverflow is more appropriate.

**Comment by Jorybraun** [comment]
@andrewimm , i tried just implementing the class and overloading the function but the new class was missing alot of attributes. 

Copying the entire file to change it was the solution that worked for me.

**Comment by zmax92** [comment]
@Jorybraun can you please post code what exactly have you changed?

**Comment by Jorybraun** [comment]
@zmax92 hey, 

So i've changed both controllers for orientationChange, essentially just multiplying the delta. 

this is working, as soon as the touchEnd event is fired, the camera snaps back to the screen orientation. Is it possible to re-sync the orientation to the new position before so that it doesnt jank back?

**Comment by MartinPham** [comment]
After some minutes checking the react-360-web and the controllers, I've found a way to implement my own camera and move it. 
It's quite simple, just implement CameraController interface (with method fillCameraProperties(position: Vec3, rotation: Quaternion): boolean) and add to react 360 instance by method addCameraController.

**Comment by MartinPham** [comment]
I've published a package so everyone can use it :)

https://www.npmjs.com/package/@martinpham/react-360-keyboard-camera-controller

check the sample folder for demo
