### ISSUE TITLE
Found 1 high severity vulnerability

### ISSUE THREAD

**Issue by logmannn** [facebook/react-360#624]
### Description

This is a bug. On installation I get 20 vulnerabilities (10 low, 2 moderate, 8 high) and after an `npm audit fix` it fixes all but one which breaks if I do an npm audit fix --force:

 SEMVER WARNING: Recommended action is a potentially breaking change

  High            Denial of Service

  Package         ws

  Dependency of   react-devtools [dev]

  Path            react-devtools > react-devtools-core > ws

  More info       https://nodesecurity.io/advisories/550

### Additional Information

* 'react-360' package version: react-360@1.0.0
* 'react-360-web' package version: react-360-web@1.0.2
* Operating System: Windows

**Comment by larrylin28** [comment]
I think this is related to react-devtools than react-360? Please report on react-devtools github page

**Comment by andrewimm** [comment]
We should remove react-devtools from being installed with every react-360-cli project, and instead provide instructions on how to add it to your project if you need it.

**Comment by logmannn** [comment]
@larrylin28 I think you are right. Closing
