### ISSUE TITLE
[Question] How to get the canvas element from React 360?

### ISSUE THREAD

**Issue by zaidSimajji** [facebook/react-360#633]
Hi, I'm trying to use WebRTC to share screen that is showing React 360. According to the WebRTC, I need to use "captureStream" function and set it as the "srcObject" of the video element. In order to do this; I need to get the canvas element.

I've tried 
```
const container = document.getElementById('container');
const canvas  = container.getElementsByTagName('canvas');
const stream = canvas.captureStream();
```

However when I do this, I get error

> canvas.captureStream is not a function

Is there a way to actually do this (a way to use the captureStream)?

**Comment by andrewimm** [comment]
`getElementsByTagName` returns a list, not an element. That is why it does not implement a captureStream method.

If you need to, you can get a direct reference to the canvas by calling `r360.compositor.getCanvas()`

**Comment by zaidSimajji** [comment]
You're right, I didn't noticed that the return value was a list. Thanks, I've managed to show the React360 in the video element now.
