### ISSUE TITLE
fbBatchedBridgeConfig is not set Error on Import

### ISSUE THREAD

**Issue by IMFIL** [facebook/react-360#639]
### Description
Importing '../actions/itemActions' causes an fbBatchedBridgeConfig is not set Error

When importing a file from a different directory, as seen in attached pictures, the application crashes. The crash is fixed when the import is removed ...

#### Expected behavior
Normal import functionality

#### Actual behavior
Crash on import

## shoppingView.js
`import { fetchItemInformation } from '../actions/itemActions'`

## itemActions.js

```
import { FETCH_SPHERE_ITEMS, FETCH_SPHERE_ITEM_INFORMATION } from './types';
import { storesRef, itemsRef, spheresRef } from '../firebaseConfig/fb';

getItems = (firebaseObject, currentSphere) => {
  var itemInSphere = {};
  var itemArray = [];
...
```
## File Structure
<img width="262" alt="screen shot 2018-12-13 at 9 36 33 pm" src="https://user-images.githubusercontent.com/16093847/49979919-3733a280-ff1f-11e8-806b-645312f27724.png">

**Comment by andrewimm** [comment]
When fbBatchedBridgeConfig is not set, that means your JS code failed to parse. It's a side-effect of being unable to initialize the underlying React Native code. This is not related to React 360

**Comment by IMFIL** [comment]
Hmm I see, I just double checked and there is no React Native dependency in the imported file nor in it's dependencies. I'll try the React Native community ! Thanks Andrew !
