### ISSUE TITLE
Can't add video event

### ISSUE THREAD

**Issue by YasHB10** [facebook/react-360#668]
I'm trying to get the moment when a video has been finished. I tried to use the video events as the documentation says but I can't add a eventlistener to my videoplayer; when I do, I get the  "addeventlistener is not fuction" error. Hope some one knows what is going on. This is my code:

const { VideoModule } = NativeModules;

CreateVideoPlayer(videoPath) {
		this.setState({ isClicked: true });

        VideoModule.createPlayer('myplayer');

        VideoModule.play('myplayer', {
			source: { url: videoPath }, 
			stereo: '3DTB', 
			volume: 1,
			muted: false,
		});

        Environment.setBackgroundVideo('myplayer');

        // the evet should be here
        VideoModule.addEventListener('onVideoStatusChanged', (event: VideoStatusEvent) => {
            if (event.status === 'finished') {
                console.log('Video is finished');
            }
        })
        
	}

**Comment by niceali** [comment]
publisher

**Comment by larrylin28** [comment]
The listener should be add to the player Instance, not VideoModule. Also, use the VideoModule exported from react-360, which has wrapped with JS utils, rather than directly using the raw native module from NativeModule.

For full guidance, please read: https://facebook.github.io/react-360/docs/photos-and-videos.html#from-react-1

**Comment by YasHB10** [comment]
@larrylin28  at the begening my code was like the documentation sais but it didn't work, after a long research I find other user had the same problem and solved as it bellows  

import { NativeModules } from react-360;
const {VideoModule} = NativeModules;

VideoModule.createPlayer('myplayer');

VideoModule.play('myplayer', {
  source: {url: '/static_assets/video.mp4'},
  loop: false,
});

Environment.setBackgroundVideo('myplayer');

you can see the link: https://github.com/facebook/react-360/issues/660

**Comment by larrylin28** [comment]
@YasHB10, I think there's an issue with the document, please use following way to get VideoModule:
`import VideoModule from 'VideoModule';`

Also as I mentioned, please make sure you are on latest version: 1.1.0.

**Comment by YasHB10** [comment]
@larrylin28  yes, I'm working on the lastest version. I did as you said but the addEventListener is still not working.  For some reazon the addEventListener is not recognized as a fuction.

**Comment by larrylin28** [comment]
@YasHB10 are you calling `addEventListener` on player as documentation? It is a function on player returned in `VideoModule.createPlayer`, not on `VideoModule`.

**Comment by YasHB10** [comment]
yes, my code looks like this

const player = VideoModule.createPlayer('myplayer');

        player.play({
            source: { url: videoPath },
            stereo: '3DTB',
            volume: 1,
            muted: false,
        });

        player.addEventListener('onVideoStatusChanged', (event: VideoStatusEvent) => {
            if (event.status === 'finished') {
                console.log('Video is finished');
            }
        });

        Environment.setBackgroundVideo('myplayer');

**Comment by larrylin28** [comment]
@YasHB10 Ah, OK, that's another document issue, the function name is `addListener`

**Comment by YasHB10** [comment]
Thanks, It work. I owe you one.

**Comment by drubio1989** [comment]
Hey @YasHB10, do you think you can copy/paste your entire `index.js` for me? I am having issues, playing video and would like to use your complete `index.js` as a template to see if I can get it to work, if you don't mind.

**Comment by YasHB10** [comment]
the index looks like this:

```
import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-360';
import Player from './src/javascript/Player';

export default class FB01 extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            videoNumber: "010",
        };
    }

  render() {
      return (
          <Player videoId="110" ButtonMessage="empezar" ref= "capsule01">
          </Player>
    );
  }
};




const styles = StyleSheet.create({
  panel: {
    // Fill the entire surface
    width: 1000,
    height: 600,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  greetingBox: {
    padding: 20,
    backgroundColor: '#000000',
    borderColor: '#639dda',
    borderWidth: 2,
  },
  greeting: {
    fontSize: 30,
  },
});

AppRegistry.registerComponent('FB01', () => FB01);
```


the player class is where I implement the video player

```
import * as React from 'react';
import {
    Environment, VrButton, Text, View, StyleSheet, NativeModules, 
} from 'react-360';
import VideoModule from 'VideoModule';


export default class Player extends React.Component {
    state = {
        isClicked: false,
        //player: null,
    }

    GetVideoPath(videoId) {
        const capsuleNum = videoId.charAt(0);
        const capsulePartNum = videoId.charAt(1);
        const capsulSubPartNum = videoId.charAt(2);
        return ('./static_assets/Video/Capsula' + capsuleNum +
            '/Video' + capsulePartNum + "_" + capsulSubPartNum + '.mp4');
    }

    CreateVideoPlayer(videoPath) {
        this.setState({ isClicked: true });
        const player = VideoModule.createPlayer('myplayer');

        player.play({
            source: { url: videoPath },
            stereo: '3DTB',
            volume: 1,
            muted: false,
        });

        player.addListener('onVideoStatusChanged', (event: VideoStatusEvent) => {
            if (event.status === 'finished') {
                console.log('Video is finished');
            }
        });

        Environment.setBackgroundVideo('myplayer');
    }

    render() {

        const VideoId = this.props.videoId;
        const videoPath = this.GetVideoPath(VideoId);
        const ButtonMessage = this.props.ButtonMessage;
        const isClickedAux = this.state.isClicked;
        if (!isClickedAux) {
            return (
                <View style={styles.greetingBox}>
                    <VrButton onClick={() => this.CreateVideoPlayer(videoPath)}>
                        <Text >
                            {ButtonMessage}
                        </Text>
                    </VrButton>
                </View>
            );
        } else {

            return (
                <View >
                </View>
            );
        }
    }
}
const styles = StyleSheet.create({
    panel: {
        // Fill the entire surface
        width: 1000,
        height: 600,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    greetingBox: {
        padding: 20,
        backgroundColor: '#000000',
        borderColor: '#555555',
        borderWidth: 2,
    },
    greeting: {
        fontSize: 30,
    },
});


```
Hope this helps you.

**Comment by timmhayes** [comment]
> @YasHB10 Ah, OK, that's another document issue, the function name is `addListener`

This was also a problem for me, so I fixed the `addListener` documentation in pull request #675
