### ISSUE TITLE
Headset cursor selector and toggling VR mode

### ISSUE THREAD

**Issue by AidenFaulconer** [facebook/react-360#670]
I would like to request two features, one for handling when a user clicks "view in VR" and "exit VR".
I would like to create an event handler to look for interaction with the 'View in VR' and 'Exit VR' feature. I need to use this to signify when to re-render components in a native 360 environment instead of the components rendered outside of react 360. I would also like to have a feature to use with VR headsets default fixed-center cursor for selection (by holding its position on an interactive element). If such features exist I have been unsuccessful in finding that information, even in the source code. 

Thanks in advance,
-Aiden

**Comment by larrylin28** [comment]
Hi @AidenFaulconer, both feature should be workable already:
#1 You can listen to event emitter of ReactInstance: 
```
r360.eventEmitter.on('entervr', () => { //do things for entering VR mode });
r360.eventEmitter.on('exitvr', () => { //do things for exiting VR mode });
```
#2 You can do this in React by yourself. Simply what you need to do is, 
   1. Listen to a button view's `onEnter` event(when cursor enter the view). Start a timer when `onEnter` is triggered, cancel it when `onExit` is triggered.
   2. When the timer timeout, trigger the interaction you want to do.
   3. You can write a re-usable React component to use it everywhere in your app.

**Comment by AidenFaulconer** [comment]
@larrylin28 

Would I need to build the event emitter as follows? or is it already built in?

`const eventEmitter = {
  events: {}, // dictionary with our events
  on(event, listener) { // add event listeners
    if (!this.events[event]) { this.events[event] = { listeners: [] } }
    this.events[event].listeners.push(listener);
  },
  off(event) { // remove listeners
    delete this.events[event]
  },
  emit(name, ...payload) { // trigger events
    for (const listener of this.events[name].listeners) {
      listener.apply(this, payload)
    }
  }
};`

And can I use that event emitter inside a defined component or does it need to be used on client.js?

**Comment by larrylin28** [comment]
@AidenFaulconer r360.eventEmitter is build-in event emitter for ReactInstance on client.js side, you can directly add a listener to it.
You can directly call a method on a react component from client.js/native module side. They are running in different thread. If you want to send event to react side from native module, you can do:
```
// The rnctx is the ReactNativeContext passed in constructor of Native Module
rnctx.callFunction('RCTDeviceEventEmitter', 'emit', [eventName, eventPayload]);
```
Then on react side, listen to the event by
```
RCTDeviceEventEmitter.addListener(eventName (eventPayload) => {
   // do your handling
});
```

**Comment by AidenFaulconer** [comment]
@larrylin28 

I tried implementing
`r360.eventEmitter.on('entervr', () => { //do things for entering VR mode });
r360.eventEmitter.on('exitvr', () => { //do things for exiting VR mode });`
and my console says that it dosen't exist, the context in which its being used in is this... 

`const r360 = new ReactInstance(bundle, parent, {
    fullScreen: true,
    cursorVisibility: "visible",
    nativeModules: [container => new NativeModule(container)],//container is the react native context passed into this native module constructor
  })

  // r360.eventEmitter.on('entervr', () => {console.warn('vr mode ON');});
  // r360.eventEmitter.on('exitvr', () => {console.warn('vr mode OFF');});

  // Listen to messages posted from react 360 components
  r360.runtime.executor._worker.addEventListener('message', (e) => onMessage(e, r360))

  // Listen to messages posted from the native module
  window.addEventListener('message', (e) => onMessage(e, r360))

  // Render background and buttons
  r360.renderToLocation(
    r360.createRoot('Experience', options),
    new Location([0, 0, 0]),
  )
`

**Comment by larrylin28** [comment]
@AidenFaulconer are you using the latest version(1.1.0)?
This event emitter is added only from this version.

**Comment by AidenFaulconer** [comment]
@larrylin28 Thank you, I saw the EventEmitter in the new source code. Now my current issue is, I want to post a message (or emit a message) to RCTDeviceEventEmitter, or whatever the context I need to grab the message from react360, FROM client.js. I only know how to listen from Client, I've tried `callFunction('RCTDeviceEventEmitter', 'emit', ['message name', [/* event args */]]);` and ` postMessage({})` but neither work, and I've tried the context `r360.runtime.executor._worker` I guess I need to know these things in plain terms...

What is the code to send messages from Client.js? 
rnctx is native context which I can listen to and post messages to, and it originates from `nativeModules: [rnctx=> new NativeModule(rnctx)]` correct? and I would post/listen to messages from native modules context via thiat right?

I can use `postMessage({})` and ` r360.runtime.executor._worker.addEventListener` to post and then listen from react 360 context right?

Thank you for taking your time to help me understand this.

**Comment by larrylin28** [comment]
Example is(you can find similar code in `VideoModule.js`:
client side:
```
this._rnctx.callFunction('RCTDeviceEventEmitter', 'emit', [
      'onVideoStatusChanged',
      {
        player: handle,
        ...videoEvent,
      }
    ]);
````
react side:
```
RCTDeviceEventEmitter.addListener('onVideoStatusChanged, (event: VideoEvent) => {
    ...
  });
```
You assumption on postMessage is wrong. Don't directly use postMessage, we use react-native message queue to handle the message from client side. That why I ask you to call `rnctx.callFunction`, which will organized the message to be able to parsed by react-native message queue.

**Comment by AidenFaulconer** [comment]
@larrylin28 I tried playing around with ReactNativeContext in my client.js to try to get it to work with callFunction. Nothing I have tried has worked, it just doesn't like anything I place before .callFunction. I tried
`ReactNativeContext.callFunction('RCTDeviceEventEmitter', 'emit', [ 'test',]);` would you explain what literally needs to be done in client.js?

**Comment by larrylin28** [comment]
I really don't understand how you get into the trouble.
As I mentioned, the rnctx in my code example is the rnctx you passed in NativeModule constructor as
```
nativeModules: [
  rnctx=> new XXXModule(rnctx),
],
```
Where you saved it in XXXModule for usage later.

If you are still having issue, can you:
1. Use Chrome Developer Tools's debugging feature, put a break point and see if you are calling callFunction on a right object. (You can add a break point here: https://github.com/facebook/react-360/blob/45486036ef690c2edf60302e48721028d22f495b/React360/js/Utils/RCTInputControls.js#L77 to see how this code work in an exist module)
2. If you still have trouble, please try send me the code you used in client.js and index.js

**Comment by AidenFaulconer** [comment]
I'm trying to send a message (in regards to an event handled on client.js) which I can listen to with RCTDeviceEventEmitter on a react 360 component. For instance, directly on client.js I want to `r360.eventEmitter.on('entervr', (e) => {
		//emit an event named 'test' in here so I can listen for it in react360 components
	});` 

and on my react 360 component I want to 
`RCTDeviceEventEmitter.addListener('test', (e) => {
			console.warn('I have received a message from client.js!');
		});`

I guess I do not understand why I would use NativeModules, and how to implement this scenario with it.

**Comment by larrylin28** [comment]
Ah, OK, I was assuming you are using NativeModule because that common case.
Directly in client.js, you can simply access the react native context by `r360.runtime.context`,
e.g.
```
r360.runtime.context.callFunction('RCTDeviceEventEmitter', 'emit', [ 'test', /*event values you passed to */]);
```

**Comment by AidenFaulconer** [comment]
@larrylin28  oh wow! I must have done something wrong the first time I tried that. Thank you very much! 

Unrelated: I love the C++ Kinect game repo you made, very cool use of OpenGL.

**Comment by Manny-Mobfish** [comment]
@larrylin28 could you tell me what would be the right import statement on the react-side to listen to an event as you mentioned?

> react side:

```
RCTDeviceEventEmitter.addListener('onVideoStatusChanged, (event: VideoEvent) => {
    ...
  });
```

**Comment by AidenFaulconer** [comment]
> @larrylin28 could you tell me what would be the right import statement on the react-side to listen to an event as you mentioned?
> 
> > react side:
> 
> ```
> RCTDeviceEventEmitter.addListener('onVideoStatusChanged, (event: VideoEvent) => {
>     ...
>   });
> ```
This is the import you will need Manny,

`import RCTDeviceEventEmitter from 'RCTDeviceEventEmitter';

If you plan to use event listeners in conjunction with native modules(to talk to react context(Not to be mistaken with react native or react360 context)), also make sure native modules are imported as well, cheers.`

**Comment by Manny-Mobfish** [comment]
Thanks!
