### ISSUE TITLE
Running local React-360 on Oculus Go

### ISSUE THREAD

**Issue by david3214** [facebook/react-360#671]
Is this a Bug or a Feature Request?
For a Bug please explain below what you did, what you expected to happen, and what actually happens.

I should be able to view my react-360 apps, running on localhost with my Oculus Go.

I can't connect my Go in such a way to view this

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

I can't find any answers online. I would like to be able to connect my Go to my computer and view my react-360 apps in development in the Oculus Go without needing to push the react-360 to an actual website. FYI I'm new into development with react-360 and the Oculus Go.

**Comment by AidenFaulconer** [comment]
Could you provide some screenshots? Make sure you're on port 8081 (http://localhost:8081/index.html) and make sure your oculus go is connected to the same network as your computer.  If none of those work make sure you have your index.html named and set-up correctly(it is the entry point for your web browser to your application).

**Comment by david3214** [comment]
I'm not sure how much a screenshot would help, my laptop can run it just fine, and I can view it through my laptop, but when I go to localhost:8081/index.html it simply says The site can't be reached.

**Comment by david3214** [comment]
I was able to use localtunnel to run the site somewhere my Go could find. Thanks for your input.
