### ISSUE TITLE
[QUESTION] How to scrolling scene in <View/> like a  web browser?

### ISSUE THREAD

**Issue by Golfklub** [facebook/react-360#673]
Hello, for this question, I want to scroll scene like a web browser, it's possible and how to do this?
***sorry for my poor language***

### Additional Information

* 'react-360' package version: [~1.1.0]
* 'react-360-web' package version: [~1.1.0]
* Operating System: [ Windows]
* Browser: [Chrome 72.0.3626.119]
* VR Device: [Out of VR]

**Comment by larrylin28** [comment]
Hi, we don't have support for a native ScrollView in React-360 yet. It'll be on our plan and implemented in near feature. 
Meanwhile, a pure js implemented ScrollView by listening to input event and moving child view with transform should be workable but may takes some of your development time if you really want one immediately.

**Comment by Golfklub** [comment]
Thank you for your answer, I'll to do this, thank you.
