### ISSUE TITLE
QUESTION: Is it possible to render more than one cylinder surface i.e. one in the front/back

### ISSUE THREAD

**Issue by drubio1989** [facebook/react-360#681]
I was wondering if it's possible to render more than one cylinder component in lieu of flat surfaces. For example, could I place one cylinder surface behind the user and then place the other behind the user? Would this be possible with current implementation?

**Comment by andrewimm** [comment]
Yes, React 360 supports as many Flat and Cylinder Surfaces as you need (https://facebook.github.io/react-360/docs/surfaces.html) and they can be rotated around the origin. This example is a demo of multiple surfaces in the same app: https://facebook.github.io/react-360/docs/example-multisurface.html
