### ISSUE TITLE
How to pass a url into Pano source instead of static assets

### ISSUE THREAD

**Issue by timothydowd** [facebook/react-360#690]
Hi,

I am trying to pull in a jpg into the pano source in index.vr.js using a url rather than static asset to display my 360 environment...  Is this possible? I am getting the error 'request animation frame handler took 183ms' which I am guessing is something to do with the url taking time to download....

Any ideas? Thanks

Here is my code:

export default class WelcomeToVR extends React.Component {
  render() {
    return (
      <View>
        <Pano source={{url:'https://farm4.static.flickr.com/3014/2846930027_e65a86f933_b.jpg'}}/>
        <Text
          style={{
            
            fontSize: 0.8,
            fontWeight: '400',
            layoutOrigin: [0.5, 0.9],
            paddingLeft: 0.2,
            paddingRight: 0.2,
            textAlign: 'center',
            textAlignVertical: 'center',
            transform: [{translate: [0, 0, -3]}],
          }}>
          hello
        </Text>
      </View>
    );
  }

--- Delete everything above this line before submitting your issue ---

**Comment by JackPu** [comment]
@timothydowd `{{uri:'xxx.jog'}}` work for you. 

https://github.com/facebook/react-360/blob/e9a1a0cd5fe0e81dd5b0192aaa765face5a3d77b/React360/js/Views/Pano.js#L312

And you should make sure that your images assets could not block request because of CROS.

**Comment by timothydowd** [comment]
@JackPu Thankyou so much : )
