### ISSUE TITLE
More detailed description of init command in CLI

### ISSUE THREAD

**Issue by vitkarpov** [facebook/react-360#692]
### Description

Hey there! 👋 

First of all, let me say thanks for a tremendous job you're doing here, guys and gals! 👍 

I'm a newcomer and would like to share small feedback about CLI.

1. `[project name]` has the same color as the terminal's background

👉&nbsp;<img width="636" alt="Screen Shot 2019-04-21 at 2 33 38 PM" src="https://user-images.githubusercontent.com/3001791/56469478-f99dd380-6442-11e9-8887-1d62f4640fcb.png">

I'm not sure if something's wrong with my terminal but wouldn't it be better to throw an error saying that `[project name]` is required?

2. There's no `-h` shortcut for `--help`

👉&nbsp;<img width="644" alt="Screen Shot 2019-04-21 at 2 26 46 PM" src="https://user-images.githubusercontent.com/3001791/56469515-89438200-6443-11e9-8a11-c1ec987d6b01.png">

It's a really common shortcut, isn't it? Also, there's no description of `--help` flag itself.

If you think this makes sense and could bring value, I'd be happy to implement 🙏 

### Additional Information

* 'react-360' package version: `1.1.0`

**Comment by JackPu** [comment]
@vitkarpov React-360 use the React-Native CLI Tool And maybe https://www.npmjs.com/package/react-native-cli help you a lot.

**Comment by vitkarpov** [comment]
@JackPu I see, you mean that this repo doesn't have any CLI, right? Thanks for pointing out, I'll close this one then 👌
