### ISSUE TITLE
Growing a community for react 360?

### ISSUE THREAD

**Issue by drubio1989** [facebook/react-360#695]
I wanted to leave this here and address this because I wanted to bring to the attention of the community that I'm currently trying to build a react 360 forum/chat/group to assist with issues that appear while developing. I've been working with react 360 on the side for about half a year dealing with issues, bugs, and work arounds and while I really enjoy react 360 and am excited for the potential it has, I've had my fair of frustrating patches working with it. 

I've used all my project knowledge to create a course on Udemy which can be found here:
[Creating VR Experiences with React 360](https://www.udemy.com/creating-vr-experiences-with-react-360). 

It doesn't have an active community (yet) but while I grow it, I kind of wanted to gauge what the community wanted in terms of dealing with issues/questions. A facebook group, discord, or something else? I'd like to try to propel this tech along and while the maintainers of this tech is j very busy making react 360 awesome, let's help ourselves while they do their job.

So any feedback or comments would be appreciated. Also, if anyone is interested in the course, I do have some discounts to offer if anyone is interested.

**Comment by ansible-comme** [comment]
I think it has been posted before, but the Reactiflux discord has a React 360 channel: https://www.reactiflux.com/

**Comment by drubio1989** [comment]
Nice! Thanks for sharing the link
