### ISSUE TITLE
smartphone head tracking not working

### ISSUE THREAD

**Issue by Pukka922** [facebook/react-360#709]
Hi,

few weeks ago I made a react 360 (version 1.0.1) test application for smartphone with cardboard and head tracking in the cardboard worked out of the box.

Now i went back to this project and realized that headtracking stopped working on my smartphone. So I created a blank new react 360 project in version 1.0.1 but still not working.
Did I something wrong or missed some configuration?

My Test Device
Iphone 6:
iOS 12.3
Chrome: 74.3729.155 and Safari

**Comment by andrewimm** [comment]
React 360 has never supported Cardboard on iPhone. It only supports devices that actually expose the WebVR API.

**Comment by Pukka922** [comment]
The Problem is not the cardboard mode, for this i used webvr polyfill. The problem is that the gyroscope camera tracking stopped working.

**Comment by Pukka922** [comment]
After a half day of research I found that apple has added a Motion & Orientation privacy setting on iOS for Safari (and Chrome?) with the iOS 12.2 update. If I enable the setting all works fine ;)

**Comment by sebas096** [comment]
Hi,
now im facing the same problem the headtracking is not working on my smarphone.
but it's curious , i have a project that i built some time before, and it works in that project.
then i take the code of this project and compile it again, and now it not working too 

im using a android
Chrome
