### ISSUE TITLE
react-360 scripts not exposed in bin field

### ISSUE THREAD

**Issue by texastoland** [facebook/react-360#711]
We're developing an [egghead course](https://github.com/eggheadio-projects/vr-applications-using-react-360/tree/zj/convert-to-yarn-workspace) with @tlakomy. Setting it up with Yarn workspaces, @zacjones93 discovered that all of the scripts are dependent on the `node_modules` hierarchy instead of being exposed through the `bin` field in `package.json`. Is there a limitation that requires this? It's unsupported behavior in the Node ecosystem including Yarn PnP and Node's own Tink.

**Comment by texastoland** [comment]
Ping @andrewimm @larrylin28 🛎 We're willing to PR.

**Comment by andrewimm** [comment]
Nothing prevents this from changing. I'll accept a PR

**Comment by texastoland** [comment]
I'll take a look with @zacjones93 tomorrow!
