### ISSUE TITLE
how to rotate model with press button of another component

### ISSUE THREAD

**Issue by Nyamkhuub** [facebook/react-360#731]
My fault, I'm super beginner in this library. Help me, please!?
### **My own simple project looks like that:**
![Screen Shot 2019-08-22 at 23 26 42](https://user-images.githubusercontent.com/40166245/63527809-5a920100-c534-11e9-8b92-40e457f4cbea.png)

My store js file:

```
import React from 'React';
/*
 * this file purpose is share data between components.
 */
const State = {
    tshirtRotate: 0,
};

const listeners = new Set();

function updateComponents() {
  
  for(const cb of listeners.values()) {
    cb()
  }
  
}

export function setCurrent(value) {
  
  State.tshirtRotate = value;
  updateComponents();
}

export function connect(Component) {
  return class Wrapper extends React.Component {
    state = {
      tshirtRotate: State.tshirtRotate,
    };

    own_listener = () => {
      this.setState({
          tshirtRotate: State.tshirtRotate,
      });
    };

    componentDidMount() {
      listeners.add(this.own_listener);
    }

    render() {
      console.log(this.state.tshirtRotate);
      return (
        <Component {...this.props} tshirtRotate={this.state.tshirtRotate} />
      );
    }
  };
}
```
I want to locate VrButton in left panel. So, If I press that button, model should rotate at the Y axis. But I couldn't understand this Store js. Please help me!!?

**Comment by drubio1989** [comment]
You have the leg work already done. On the panel where your button is defined do this:

<VrButton onClick={() => this.setCurrent(90)}

Basically what this comes down to is an imitation of Redux and Flux architecture. Try reading this snippet from Redux to get a picture of what is going on [Data Flow](https://redux.js.org/basics/data-flow).

**Comment by Nyamkhuub** [comment]
@drubio1989  thanks man!
