### ISSUE TITLE
Couldn't load 2d image 

### ISSUE THREAD

**Issue by Nyamkhuub** [facebook/react-360#742]
Hello developers, I need help for my small issue. I exactly don't know why doesn't work. I want to add some 2D images in my project. But I couldn't. My code is here:
```
<View>
    <Image source={{uri: 'https://freeicons.io/laravel/public/uploads/icons/png/20642841761530177259-128.png'}} />
</View>
```
See nothing in my project view. How to solve this problem? help me?

OR

How to add Fontawesome library to my project. For example:
I want to use [this library](https://github.com/FortAwesome/react-native-fontawesome). But I also couldn't. Help me? thank you very much!

**Comment by drubio1989** [comment]
Try setting a width and height for your image. That should do the trick unless you have an error in the console

**Comment by Canopix** [comment]
Put a style on your image, with width and height.

**Comment by Nyamkhuub** [comment]
@drubio1989 @Canopix  thanks! But I want using Fontawesome. How to use it??
