### ISSUE TITLE
How exit from 360 mode?

### ISSUE THREAD

**Issue by zsaidov** [facebook/react-360#790]
### Hi!
I want to exit 360 mode fails, tried using
  **`r360._onExitVR()`** 
it did not help.
Could somehow differently?
Thank you!

**Comment by Justinohallo** [comment]
Are you trying to stop the R360 instance?

**Comment by jrjones** [comment]
Sounds like he wants to exit VR mode programatically.

_onExitVR() is an event that fires when the user initiates the exit, not a function/method that initiates it.

**Comment by zsaidov** [comment]
@Justinohallo yes, stop and exit

**Comment by Justinohallo** [comment]
Is there a method that can do this? I want to be able to click a VR event, turn off the environment and be redirected to a page.

**Comment by zsaidov** [comment]
I found a solution:
```
 const display = reactInstance.vrState.getCurrentDisplay();
if (display && display.isPresenting) {     
   display.exitPresent();       
}
```
