### ISSUE TITLE
Poor performance?

### ISSUE THREAD

**Issue by FezVrasta** [facebook/react-360#88]
Hi, I'll probably attach a repro anytime soon, but I wanted to check with you if you were already aware of poor performances when it comes to update the "markup" of a scene.

For instance, I have a set of colored spheres positioned in the 3d space, and when I gaze at one of them, all the spheres of the same color should stay colored while the rest should become black.

When I run the app and I gaze at a sphere, it takes several seconds to highlight the selected set of spheres and it flickers a lot.

Same thing happens with the movement of the camera, I tried to make the camera move when I use the analog of the Oculus, but it lagged a lot, I mean, it took few minutes to perform any update.
I tried to move the objects in the scene instead of the camera to see if it helped, but the result is almost the same.

Thank you for your help!

**Comment by andrewimm** [comment]
I'd love a repro case. I haven't seen anything like what you're describing, but if there's a problem I'd want to address it.

**Comment by FezVrasta** [comment]
Ok I'll try to set one up for the next week.

**Comment by mikearmstrong001** [comment]
Thank you!

This information is useful because there are methods in constructing React scenes that cause more work to be done in the react core code than is necessary. If we can help you avoid these then that is super useful for your future applications. Alternatively if we have some limitations we are very keen to identify them and fix them.

**Comment by FezVrasta** [comment]
I have a repro ready, I'm waiting the approval to share it from my company. I guess I'll share it this week

**Comment by FezVrasta** [comment]
Hey @mikearmstrong001 and @andrewimm, I had the go ahead from my team, here's the repository with the problems:

https://github.com/FezVrasta/vr-repro

You should be able to hover with your mouse over any of the structures (spheres and cylinders) and highlight the selected color (making the others turn black-ish).

But in practice it lags really badly (isn't much better neither if I get rid of the 60fps update I used to simulate the new data coming from my other module that takes care to animate those structures).

I hope you find out we did something very stupid and it's not a problem with React VR 😅

**Comment by mikearmstrong001** [comment]
Much appreciated.
As you have all the logic and setState in the one component, every time an event for Enter or Exit is fired the full component hierarchy will be recreated from the root. You should look to restructuring the hierarchy so that when a setState is called only that component is re-rendered

You should look to only cause a rerender on the most leaf components you can get away with.

Let me know if this helps but should be able to provide a better example later in the week

```
class Vertex extends Component {
  render() {
    return (
      <Sphere
         onEnter={() => this.setState}
         onExit={() => this.setState}  
     )
   }
}

class Vr extends Component {
  render() {
    return (
      <View>
        <Vertex>
      </View>);
  }
}
```

**Comment by FezVrasta** [comment]
Thank you, I'm not working on it at the moment, I'll see if I can dedicate some time to it in the next days. But probably you'll be faster than me.

**Comment by FezVrasta** [comment]
By the way, in my full code, all the vertices move at the same time, so I don't think your suggestion would help... Or do I miss anything?

**Comment by mikearmstrong001** [comment]
I will run the code in the next couple of days. But a cursory look at the data set indicated a large number of vertices > 1000 which would create spheres. All would what to move when one is selected. 
Is my overview correct ?

**Comment by FezVrasta** [comment]
The demo code has a set of spheres linked together with cylinders. When you hover over one of them, the ones of the same color gets highlighted.

In the original code, all this happens while the spheres move around the scene

**Comment by FezVrasta** [comment]
Hi @mikearmstrong001, I'm here at React Europe, cool talk 😉 Did you have time to look at this?

**Comment by FezVrasta** [comment]
Any reason to close this? Thanks

**Comment by FezVrasta** [comment]
Thanks!
